package day21;

import java.util.HashMap;

public class Day21Task2 {
    public static void main(String[] args) {
        String[] lines = INPUT.split("\n");
        HashMap<String, Calculatable> exprs = new HashMap<>();
        for (int i = 0; i < lines.length; i++) {
            String[] parts = lines[i].split(": ");
            String name = parts[0];
            String expr = parts[1];
            int space = expr.indexOf(' ');
            if (space >= 0) {
                char op = expr.charAt(space + 1);
                String first = expr.substring(0, space);
                String second = expr.substring(space + 3);
                exprs.put(name, new Calculatable(name, first, second, op));
            } else {
                int val = Integer.parseInt(expr);
                exprs.put(name, new Calculatable(name, val));
            }
        }
        System.out.println(exprs.get("root").toSubtractCalculatable().getHumnFor(exprs, 0));
    }

    private static class Calculatable {
        private String name;
        private String firstExpr;
        private String secondExpr;
        private char op;
        private Long result;
        private Object firstVal;
        private Object secondVal;
        private boolean humn;

        public Calculatable(String name, String firstExpr, String secondExpr, char op) {
            this.name = name;
            this.humn = name.equals("humn");
            this.firstExpr = firstExpr;
            this.secondExpr = secondExpr;
            this.op = op;
        }

        public Calculatable toSubtractCalculatable() {
            return new Calculatable(name, firstExpr, secondExpr, '-');
        }

        public Calculatable(String name, long value) {
            this.name = name;
            this.humn = name.equals("humn");
            this.result = value;
        }

        public Object getResultOrSelfIfHumn(HashMap<String, Calculatable> exprs) {
            if (humn) {
                return this;
            } else if (result != null) {
                return result;
            } else {
                if (firstVal == null) {
                    firstVal = exprs.get(firstExpr).getResultOrSelfIfHumn(exprs);
                    secondVal = exprs.get(secondExpr).getResultOrSelfIfHumn(exprs);
                }
                if (firstVal instanceof Long firstVal && secondVal instanceof Long secondVal) {
                    result = switch (op) {
                        case '+' -> firstVal + secondVal;
                        case '-' -> firstVal - secondVal;
                        case '*' -> firstVal * secondVal;
                        case '/' -> firstVal / secondVal;
                        default -> throw new IllegalStateException();
                    };
                    return result;
                }
                return this;
            }
        }

        private long getHumnFor(HashMap<String, Calculatable> exprs, long v) {
            if (humn) {
                return v;
            }
            if (firstVal == null) {
                firstVal = exprs.get(firstExpr).getResultOrSelfIfHumn(exprs);
                secondVal = exprs.get(secondExpr).getResultOrSelfIfHumn(exprs);
            }
            if (firstVal instanceof Long val) {
                long result = switch (op) {
                    case '+' -> v - val; // val + x = v
                    case '-' -> val - v; // val - x = v
                    case '*' -> v / val;// val * x = v
                    case '/' -> val / v; // val / x = v
                    default -> throw new IllegalStateException();
                };
                return ((Calculatable) secondVal).getHumnFor(exprs, result);
            } else if (secondVal instanceof Long val) {
                long result = switch (op) {
                    case '+' -> v - val; // x + val = v
                    case '-' -> v + val; // x - val = v
                    case '*' -> v / val;// x * val = v
                    case '/' -> v * val; // x / val = v
                    default -> throw new IllegalStateException();
                };
                return ((Calculatable) firstVal).getHumnFor(exprs, result);
            } else {
                throw new IllegalStateException("booo!");
            }
        }
    }

    public static final String INPUT_TEST = "root: pppw + sjmn\n"
            + "dbpl: 5\n"
            + "cczh: sllz + lgvd\n"
            + "zczc: 2\n"
            + "ptdq: humn - dvpt\n"
            + "dvpt: 3\n"
            + "lfqf: 4\n"
            + "humn: 5\n"
            + "ljgn: 2\n"
            + "sjmn: drzm * dbpl\n"
            + "sllz: 4\n"
            + "pppw: cczh / lfqf\n"
            + "lgvd: ljgn * ptdq\n"
            + "drzm: hmdt - zczc\n"
            + "hmdt: 32";

    public static final String INPUT = "rgfg: 7\n"
            + "dvfr: 2\n"
            + "srjl: 15\n"
            + "lqvd: sqbt * rvzp\n"
            + "rqcs: gpvh * cdfd\n"
            + "vclj: 2\n"
            + "blts: 2\n"
            + "qwhw: 19\n"
            + "lzcr: 2\n"
            + "qdnp: 1\n"
            + "fqtv: 20\n"
            + "mgqz: ghcc + btql\n"
            + "qzzz: 4\n"
            + "svqt: djpj + zghf\n"
            + "wpjg: 4\n"
            + "rvld: 9\n"
            + "fcgn: 7\n"
            + "cmbz: nmtm * twng\n"
            + "mbzr: jqgb + vjbq\n"
            + "fjtt: 3\n"
            + "zztp: gjbl * lcdp\n"
            + "qwnr: 7\n"
            + "qdwh: 2\n"
            + "dbbq: ltth + dvhf\n"
            + "jdzd: 3\n"
            + "wgcl: wwnm + pmhr\n"
            + "twrz: 2\n"
            + "twnr: brqf - tbgb\n"
            + "gfcv: 2\n"
            + "ntts: jtpv + hhgc\n"
            + "nlhj: 16\n"
            + "zbwq: 1\n"
            + "cjbs: pqcv * dssn\n"
            + "gwwv: lgjj - dblz\n"
            + "dfdb: 11\n"
            + "phct: 14\n"
            + "prrh: humn - dgzv\n"
            + "sdvl: wdlt + qlpq\n"
            + "jrgf: 19\n"
            + "vnrj: hgml * pdhf\n"
            + "nfbv: 1\n"
            + "nbrl: cghl + pvpg\n"
            + "cndb: 4\n"
            + "dflh: 8\n"
            + "hjzq: fjgs + pbfz\n"
            + "csmf: fqcq + hzrw\n"
            + "ghjh: srhw + qcrz\n"
            + "rwft: 3\n"
            + "mngt: 17\n"
            + "pmfb: rpwt - zqtg\n"
            + "ptpr: rjrz * zcgl\n"
            + "nwhw: sflg + cfhr\n"
            + "csdm: 2\n"
            + "rqwr: ghpc * jqcb\n"
            + "lwqf: wrms + gdvv\n"
            + "fcbw: 9\n"
            + "ssst: 3\n"
            + "tjzf: 2\n"
            + "nrzl: 3\n"
            + "qwjv: qhwt + ljls\n"
            + "rjrz: hdrv - tdrq\n"
            + "lwgl: bspl * gwcc\n"
            + "psgg: nqvr * nbrf\n"
            + "dnnc: wgfv * flmg\n"
            + "nnbn: 4\n"
            + "stjg: 3\n"
            + "qfcj: 5\n"
            + "bhlf: glmn - ghbv\n"
            + "hqms: ftjw * jdzd\n"
            + "zqtg: zcvf * qqdw\n"
            + "whrp: 3\n"
            + "jnrp: 3\n"
            + "vdtn: 3\n"
            + "mfdh: vrqd / bfrj\n"
            + "gdjq: 2\n"
            + "srtc: mpwf * fjbm\n"
            + "tqbd: rvnp * tqmf\n"
            + "gmsq: 2\n"
            + "fcll: pjhq * smhw\n"
            + "ggvp: 3\n"
            + "nbgd: gfcv * qllt\n"
            + "mzdr: wpnv * hgjz\n"
            + "qrnn: 1\n"
            + "qdnv: plqp + cgqq\n"
            + "ppsg: 17\n"
            + "bwwd: rsvl + jqbn\n"
            + "jjqr: 2\n"
            + "hrff: 3\n"
            + "lfzr: tjwr + nttc\n"
            + "hdjc: 5\n"
            + "qntd: qqgz * dcjg\n"
            + "gbtz: rzww * gwsp\n"
            + "fpww: 1\n"
            + "cbmt: bzzj * qwmz\n"
            + "dlqm: 5\n"
            + "sdmw: ccfw * rvjz\n"
            + "ccfw: 2\n"
            + "pprc: qrwq - rhwf\n"
            + "bcns: 17\n"
            + "fwtq: 7\n"
            + "mbqq: rmds + mlvg\n"
            + "flmg: 4\n"
            + "sdgl: lvdf * hwgq\n"
            + "fjvg: 10\n"
            + "wmwp: 5\n"
            + "jsrm: qwjv + dmss\n"
            + "tdzt: qqrj + rvld\n"
            + "mnmz: 15\n"
            + "zvpf: 9\n"
            + "wlcw: 2\n"
            + "snpf: 4\n"
            + "vbgr: zcsg + bvsd\n"
            + "sldw: 4\n"
            + "cbfr: dstt + htnp\n"
            + "fzlh: 7\n"
            + "vmqf: nvtp * wltb\n"
            + "fwtm: 3\n"
            + "psrv: nppr + fzqg\n"
            + "vhmg: rwpc * zqpf\n"
            + "jhgj: tfzj + cqgg\n"
            + "ljjw: qstq * srmh\n"
            + "fvsc: 13\n"
            + "npbb: 16\n"
            + "jrzz: hvnn * pqmv\n"
            + "nllb: gtwh + phpm\n"
            + "gdtg: 2\n"
            + "djwv: 3\n"
            + "hzfq: 5\n"
            + "hbtr: rlfm * jjfs\n"
            + "mwcn: bzwb - fszz\n"
            + "bdvs: 2\n"
            + "swfh: pffh - mngt\n"
            + "cwpd: gmqr + jdvs\n"
            + "jwbz: tjzb + bnzd\n"
            + "gdnm: hgsz + nnzq\n"
            + "vhpz: 3\n"
            + "mspm: ffvm + bgvw\n"
            + "rwpq: 3\n"
            + "pstq: pzmw * bdrz\n"
            + "zvqj: 13\n"
            + "dgwp: hsgz + zrdh\n"
            + "cnfz: cdpt * dftf\n"
            + "mcqt: 15\n"
            + "vczt: 2\n"
            + "hzjc: mngm + nnbn\n"
            + "hgvb: jdln * cmwq\n"
            + "pbfz: twhc * hzfq\n"
            + "hcbm: lmbh * nghs\n"
            + "mpsq: 6\n"
            + "qmlb: 5\n"
            + "vsht: 2\n"
            + "swzv: 2\n"
            + "twbr: vmrd * dbhn\n"
            + "jrzt: jbzp * pptp\n"
            + "pvdj: 12\n"
            + "hbvj: 2\n"
            + "rmzz: 20\n"
            + "hsdv: 12\n"
            + "vqlq: pcgq * wmgs\n"
            + "gfzq: 1\n"
            + "lvpz: 2\n"
            + "dvps: zlwg * twbr\n"
            + "zjmm: 5\n"
            + "btnz: 4\n"
            + "qbmj: 2\n"
            + "gqjl: pcqg + fqsj\n"
            + "ljrh: zmzm * hlvz\n"
            + "wtmp: cmlw * lcgc\n"
            + "jgmw: qvnw - lvdq\n"
            + "wtjn: jzpt + fssd\n"
            + "bcdw: mdtt * nlhj\n"
            + "gvmc: wqql * zmdv\n"
            + "brfl: twhf * rttd\n"
            + "lzms: 10\n"
            + "jzzh: mtgv * ghdc\n"
            + "srmh: ljcq + qcgv\n"
            + "zfvv: rqqh * lccm\n"
            + "wnqs: sbws + ghjh\n"
            + "brqf: dgjt / sslm\n"
            + "wthg: 2\n"
            + "lsqn: 5\n"
            + "zhfp: 3\n"
            + "mdgp: nwhw + schl\n"
            + "nghs: btpv + hdvv\n"
            + "ddzp: 4\n"
            + "pmpz: vbfp / zjsl\n"
            + "stvp: qrzd + swcd\n"
            + "cscd: wzrd / lbjz\n"
            + "pgqn: jrms * wthg\n"
            + "ntps: mmmz * ccvg\n"
            + "vqvj: qlqd + zhvb\n"
            + "mccc: 2\n"
            + "jrns: bfht / frbf\n"
            + "gscm: rqqr - qgjv\n"
            + "lztm: 2\n"
            + "vmrs: 3\n"
            + "bshf: vclj * fghj\n"
            + "ftws: jqdh + clzz\n"
            + "hsfn: 3\n"
            + "vrmz: 4\n"
            + "ldmq: 3\n"
            + "vftg: 4\n"
            + "gjcf: 17\n"
            + "vdgt: plss * cvlv\n"
            + "cfhb: 3\n"
            + "cszp: 3\n"
            + "rdgc: bjlm * nzbp\n"
            + "sqfq: drhf * jrtl\n"
            + "bzcg: wbjh * ntqb\n"
            + "jfjl: 12\n"
            + "bwlt: 3\n"
            + "qrzc: vbqv + gfvg\n"
            + "tqrq: rhqd + grwm\n"
            + "wgqf: 2\n"
            + "dnps: tdrt * nnhr\n"
            + "cpbb: ddzp * whfw\n"
            + "mjbb: qgvq * pjjl\n"
            + "ncdq: 10\n"
            + "jgwm: 14\n"
            + "nzjl: 7\n"
            + "btpv: 10\n"
            + "wpnv: 7\n"
            + "hpdf: 3\n"
            + "pdhf: 19\n"
            + "cqjn: 5\n"
            + "tbvv: cscd - sswr\n"
            + "bztb: 1\n"
            + "pzzj: 5\n"
            + "thtp: 10\n"
            + "chch: cjgq * qzjh\n"
            + "hwgq: cqtm + sdgr\n"
            + "zqfn: 3\n"
            + "vdvn: mgtq + lnvw\n"
            + "cqdq: zcng * bvcg\n"
            + "fjtr: jfhl * flqb\n"
            + "jgss: 6\n"
            + "qjwn: fmgz + gdbm\n"
            + "rmpm: 2\n"
            + "jfsw: jfmf + sqpz\n"
            + "zggj: 2\n"
            + "vvcp: 6\n"
            + "sptr: 2\n"
            + "qwzs: 11\n"
            + "hdvv: 3\n"
            + "rcwg: 1\n"
            + "hmwv: 2\n"
            + "fnwh: 4\n"
            + "msvn: 3\n"
            + "zbvc: 2\n"
            + "vfcd: 13\n"
            + "pmhr: 18\n"
            + "vrlm: 7\n"
            + "bttt: pzzj + bdvs\n"
            + "sghh: 2\n"
            + "cfnb: whpb - cvnw\n"
            + "prlg: mrgt * npmm\n"
            + "pgtf: nzhg - pmgp\n"
            + "gtqq: vbmn + bfbg\n"
            + "fpmw: jzbr * vttj\n"
            + "bhwf: tlls * vjhb\n"
            + "fjsr: mqjq * rwsf\n"
            + "lfcv: rzgr * tlgc\n"
            + "nhdj: sptr + dtbw\n"
            + "qlhb: 5\n"
            + "chjh: qmcs * hlqz\n"
            + "cqqs: bhlt + fvsc\n"
            + "pjsj: 3\n"
            + "hrht: 3\n"
            + "gpjv: qdff - pqbm\n"
            + "dnqm: 5\n"
            + "qztw: 2\n"
            + "jpmf: 3\n"
            + "rtlh: 13\n"
            + "ssnv: 1\n"
            + "ggjp: 2\n"
            + "jzlz: 5\n"
            + "wgfv: 13\n"
            + "msgn: 11\n"
            + "wbfd: chjh - cqpp\n"
            + "nwwl: hdhf / rjmq\n"
            + "glcm: 2\n"
            + "fnst: 1\n"
            + "lgjj: lwdc * vsfl\n"
            + "wnzj: mbvs * pmpz\n"
            + "jdln: 7\n"
            + "mhlb: 4\n"
            + "lbns: 2\n"
            + "tvrz: 2\n"
            + "srqz: 4\n"
            + "mwjf: 2\n"
            + "qfpp: 5\n"
            + "lqhf: rjsw * gstp\n"
            + "hqrj: 2\n"
            + "cdcs: 2\n"
            + "wgmg: 2\n"
            + "fnwv: 2\n"
            + "vqht: zbfv + fpmw\n"
            + "glll: 2\n"
            + "plqp: tzpq * dvqb\n"
            + "ntbb: wssz / qbpg\n"
            + "wqgb: smzc + fdls\n"
            + "lqml: 13\n"
            + "dftf: cdvz * rbwv\n"
            + "ppnq: 3\n"
            + "gqnr: nlds + ztmr\n"
            + "zhnq: rnfs * bdlq\n"
            + "dgzd: 4\n"
            + "slhl: pdrs * lbfp\n"
            + "bmcl: 2\n"
            + "dmwb: qwzs * crzf\n"
            + "qrwq: 13\n"
            + "tztv: hqvh * nvcm\n"
            + "dlwf: qfcj * bghw\n"
            + "rmpj: vtmz + tlcq\n"
            + "gstp: 4\n"
            + "ljfz: 4\n"
            + "dfgr: mdgp - ctmz\n"
            + "fdqw: 2\n"
            + "czcc: 2\n"
            + "qrsz: wjcv * dmvf\n"
            + "dbjv: hpws + gwwq\n"
            + "vmtm: 10\n"
            + "rzsp: rvfq * mjth\n"
            + "plhm: jtcf * qwnr\n"
            + "cswl: 3\n"
            + "gtws: 3\n"
            + "llfp: 2\n"
            + "vrtf: 2\n"
            + "lvrw: qfbw * fwtm\n"
            + "wjcv: zhfp + gphd\n"
            + "mhtt: 7\n"
            + "qwqr: 5\n"
            + "lgtm: 6\n"
            + "zcsg: hrgr - wdvc\n"
            + "pcvg: 2\n"
            + "wbjh: 4\n"
            + "mddb: 10\n"
            + "whqs: nnww - sjbb\n"
            + "bghw: 2\n"
            + "hfhs: 2\n"
            + "hrdr: ptpr / hfvl\n"
            + "cbps: 5\n"
            + "cvnw: hqrj * bqzd\n"
            + "lrtc: 2\n"
            + "lpqf: 9\n"
            + "fzzr: mnlm / ffqb\n"
            + "ddrd: nsjt * nbbh\n"
            + "cmww: 2\n"
            + "rbwv: 3\n"
            + "ptsv: 4\n"
            + "mgnn: wwdw + fqhb\n"
            + "dchl: cqqs * bfvw\n"
            + "nmhp: qzlc * dqsh\n"
            + "mwvb: 2\n"
            + "pqjn: sptb + dwdv\n"
            + "vczn: lqhf + msvn\n"
            + "fwqc: hmgg * gmvp\n"
            + "qfdp: 3\n"
            + "ndmb: gjcf * sjcc\n"
            + "cmwq: 7\n"
            + "qqcj: rlgp + cjbs\n"
            + "mhrs: gdwf * ddft\n"
            + "nsjt: srcq + wbtj\n"
            + "fgdp: 2\n"
            + "rcvq: qdnv / pjdc\n"
            + "lcpv: 3\n"
            + "jtfh: wljc + mrmb\n"
            + "ljst: 12\n"
            + "sngd: gfht * ldmq\n"
            + "vrqd: jzwl * mgcr\n"
            + "mvzw: lrtv * gmnh\n"
            + "lphb: qztw * zsqv\n"
            + "mjlf: fcnp * gjnm\n"
            + "znlp: 3\n"
            + "pvpg: 3\n"
            + "qvvl: 4\n"
            + "qcjh: 1\n"
            + "zhpj: 3\n"
            + "rwln: 2\n"
            + "bhlt: ljfz + cvsb\n"
            + "ssrd: gqzs * fdfc\n"
            + "pmzl: fwgv + ffht\n"
            + "spgm: 4\n"
            + "fzcp: ffjf / ffrp\n"
            + "qvpb: 11\n"
            + "fcfg: 12\n"
            + "vcdh: jrpn * bjrp\n"
            + "zgcp: qswg + wvdp\n"
            + "lnrm: 3\n"
            + "hgws: dtpj * zmlm\n"
            + "bzzj: 2\n"
            + "rtsj: 4\n"
            + "pjhg: 3\n"
            + "rsgc: lqnv - zbwq\n"
            + "ffht: hrtf * mrqj\n"
            + "hjnb: lwdd + lcpv\n"
            + "mgtq: lmhb * bzcg\n"
            + "fznc: tgtn / lsjr\n"
            + "mwmn: stjg * tdhc\n"
            + "pzgm: qdwh * cszp\n"
            + "rlgn: djwv * qlvd\n"
            + "zgnb: 1\n"
            + "svqz: 4\n"
            + "tfgf: gftc * wpjg\n"
            + "dqsh: bwpt + fdsd\n"
            + "trrg: hdqb + tndw\n"
            + "ljdh: wnql * jlbc\n"
            + "plvr: mccw * rnnb\n"
            + "clhr: 2\n"
            + "wtcl: 15\n"
            + "sjbb: 2\n"
            + "rdsh: pfnq * crbz\n"
            + "sjst: gftd - fgnf\n"
            + "zdbr: 4\n"
            + "hcwj: fzcs + qmhd\n"
            + "zghf: 18\n"
            + "vprq: 3\n"
            + "qpmm: 2\n"
            + "cgcm: 16\n"
            + "zcvf: 2\n"
            + "wjbs: 2\n"
            + "wvhv: vfnb + rgsw\n"
            + "mmwd: 4\n"
            + "tdhc: 5\n"
            + "lpgm: 3\n"
            + "fnbg: 5\n"
            + "ftjw: 2\n"
            + "gpfh: 2\n"
            + "qqdw: wvbv + sgcs\n"
            + "nhnr: smng + cbmt\n"
            + "dtbw: 17\n"
            + "vdtv: 11\n"
            + "bfsr: 7\n"
            + "zhvs: vrjr + vgrz\n"
            + "jhdj: 9\n"
            + "cbww: cswl + tmcv\n"
            + "grjp: 2\n"
            + "gcjw: 2\n"
            + "gftd: zdbr * vqwj\n"
            + "lpzc: 6\n"
            + "hbqn: vnsg + mtwb\n"
            + "vghh: nsjf + nfsr\n"
            + "jrms: mcjw + tqtf\n"
            + "jfpm: 3\n"
            + "lsls: bbvf * plvr\n"
            + "hwhq: 1\n"
            + "bjrg: nsrh * vqlq\n"
            + "gmvp: 17\n"
            + "qtnr: 2\n"
            + "mjth: 2\n"
            + "sjcb: vmqq + zjmm\n"
            + "lscz: 7\n"
            + "ghlb: rlmb * vqvj\n"
            + "bpgv: 6\n"
            + "nvfn: mcqt * hbqn\n"
            + "gmqr: 9\n"
            + "zvhb: 14\n"
            + "jrcw: 2\n"
            + "nspv: 5\n"
            + "gpwl: vdvj + rldj\n"
            + "rlrl: 7\n"
            + "mvhj: cwdv + tnnn\n"
            + "zcdn: 3\n"
            + "lcnr: 3\n"
            + "fwgb: 15\n"
            + "trfn: mddb + hwhq\n"
            + "crbz: 2\n"
            + "sgzm: qcdj + gdlw\n"
            + "msqz: bgtj * nbfv\n"
            + "jtcf: hfhj + nzlq\n"
            + "rtsq: qzmg + mzzb\n"
            + "brrj: jpmf * gcfs\n"
            + "ghpc: fwgb - qvvl\n"
            + "tbqf: 3\n"
            + "bzgg: cspq / vrpg\n"
            + "zngr: 1\n"
            + "mdgb: drmp * qpmm\n"
            + "sdjg: hffl / nszh\n"
            + "lwvv: 2\n"
            + "sftz: wtjs * cpmq\n"
            + "jntf: jgsl - cbps\n"
            + "hlqz: 3\n"
            + "hhgc: sdmc * wdbb\n"
            + "gmnh: 5\n"
            + "cchl: 3\n"
            + "bdrg: ppsg * scbg\n"
            + "vsvz: nmhf - ljdh\n"
            + "nsjf: zvpf * cmhb\n"
            + "rwsf: 2\n"
            + "gbjs: qcbb + swgc\n"
            + "qfzw: 2\n"
            + "mfrp: nhdj + rzft\n"
            + "znld: 3\n"
            + "ffjf: tcvd + zvrd\n"
            + "zsrp: 7\n"
            + "nccv: pbvd * qpph\n"
            + "flqb: llfr + cnvt\n"
            + "tvjw: hmjp / gpdt\n"
            + "zcpw: 10\n"
            + "qntz: 4\n"
            + "rvzp: pqtg + zvfv\n"
            + "rvnp: 2\n"
            + "cmgn: 4\n"
            + "qwpv: lswq * jbcv\n"
            + "jrdb: 2\n"
            + "fcvt: 4\n"
            + "wdlt: pjfq * dctj\n"
            + "rglz: fbwt + lcqz\n"
            + "mbtl: 1\n"
            + "cqtg: 10\n"
            + "mqbl: bhwf * qsfc\n"
            + "lcqz: fsmj * cnsq\n"
            + "tqzr: drhv + jnvz\n"
            + "pqtg: 10\n"
            + "nttc: rhrj * zgcp\n"
            + "zhvb: 2\n"
            + "qzwc: djrf / hfpc\n"
            + "srrm: dflh - vtvg\n"
            + "pwmb: 4\n"
            + "fhlf: znjj - ltsl\n"
            + "qvhr: cqtg * wnst\n"
            + "wlgz: 2\n"
            + "tdwg: brfl * wvhv\n"
            + "pbvd: gmjr + jfcb\n"
            + "bbvj: 6\n"
            + "zlvc: 2\n"
            + "pvfj: 13\n"
            + "lhzf: grcw + pcqm\n"
            + "gcfs: 7\n"
            + "hhlj: 5\n"
            + "sltp: 3\n"
            + "hmpv: jnlr + nnvq\n"
            + "rscq: 3\n"
            + "jtrl: jwdd * rzmz\n"
            + "fssd: clzs / srqz\n"
            + "nlgh: 3\n"
            + "hlvz: 2\n"
            + "gwcc: 2\n"
            + "dtdq: vfcd * lmjt\n"
            + "bncj: zhvl / mccc\n"
            + "mvwq: cqdq + jdcf\n"
            + "ltth: zjvp * sghh\n"
            + "hpws: spdl * jqhz\n"
            + "mwlp: gght / fflz\n"
            + "qpvs: wdsp + tcgr\n"
            + "vzhf: 3\n"
            + "mdtt: 2\n"
            + "sbwg: 1\n"
            + "lthv: vgrp * fvmw\n"
            + "sptb: mgnn + fpwh\n"
            + "mmwn: gpmm * hrht\n"
            + "swgs: 2\n"
            + "qgmn: 3\n"
            + "gpdt: 2\n"
            + "pblj: 2\n"
            + "pcqg: 3\n"
            + "pqmv: 3\n"
            + "fjgs: gqcp * blwq\n"
            + "bghj: mprs + nlrv\n"
            + "sgrl: 13\n"
            + "mljq: vprq * znld\n"
            + "mlwh: stnp * bwww\n"
            + "lfnl: 9\n"
            + "jzbr: 19\n"
            + "fsvr: 3\n"
            + "vmqq: 6\n"
            + "bgjv: gtdq * whqs\n"
            + "nvdr: lppg * qqht\n"
            + "dsff: bwtn - jrzt\n"
            + "qdfc: jpsh * wnfl\n"
            + "sspm: 3\n"
            + "qhzt: wnqs - rglw\n"
            + "ccvg: qwbz * blts\n"
            + "rzww: 2\n"
            + "sqbt: 2\n"
            + "scjs: 2\n"
            + "bzgd: cchl * rdtm\n"
            + "cdtm: 6\n"
            + "hjjg: 5\n"
            + "cghl: 12\n"
            + "hdqb: fsld * cbtc\n"
            + "jrpn: rjpv + lvrw\n"
            + "tzpq: 5\n"
            + "gmsv: 3\n"
            + "gpzm: sgrl + dvfh\n"
            + "bzwb: brtg / mtld\n"
            + "lvng: lffl * bnrc\n"
            + "wsfz: blcp * lqss\n"
            + "wtjs: ctmh * zqmg\n"
            + "rswf: 7\n"
            + "zcng: 3\n"
            + "tmqr: 3\n"
            + "lnqw: 4\n"
            + "ljls: 11\n"
            + "pchs: 4\n"
            + "smhw: 7\n"
            + "vlzv: 15\n"
            + "qmhd: fpvq * cwpd\n"
            + "qdmq: qwjj / zlvc\n"
            + "pgml: 5\n"
            + "jrlt: dfdb * jrcw\n"
            + "vjhb: cbfr + qrsz\n"
            + "zjsl: 2\n"
            + "qfbw: 3\n"
            + "jdns: lgzw + rqnw\n"
            + "pfpq: nnrm + bnnn\n"
            + "jzpt: 3\n"
            + "gspg: 2\n"
            + "sbws: hbtr - qmlb\n"
            + "zqpr: ppmg * gwvt\n"
            + "vnsg: 3\n"
            + "dcpz: 3\n"
            + "mbnh: 13\n"
            + "ghts: dcnc * vfbz\n"
            + "qwjj: zvtf / nbjw\n"
            + "vdvj: pstq * zsrf\n"
            + "pjdm: bdhm * hnwt\n"
            + "cmhb: 2\n"
            + "wghj: 17\n"
            + "czhg: sngd + vttc\n"
            + "ttpl: 17\n"
            + "sbnm: 4\n"
            + "cqhh: 5\n"
            + "vbmn: 3\n"
            + "fbnt: zctw + qflv\n"
            + "qbbm: rgfg + jrlt\n"
            + "zdpc: bncj * czhg\n"
            + "tldr: 5\n"
            + "jjfs: 7\n"
            + "jrtl: 4\n"
            + "nlrv: 2\n"
            + "drhg: jlst * hdjc\n"
            + "hrtf: hhdw + qdnp\n"
            + "humn: 2076\n"
            + "ghbv: jgmw * jdtn\n"
            + "scbg: gjgt * dcvd\n"
            + "fzqn: mvcg * lpzc\n"
            + "fwgv: gslg * qlhb\n"
            + "tglq: 6\n"
            + "lzcz: 11\n"
            + "gzpp: nmds + qtvv\n"
            + "brtg: ntbb + dnmd\n"
            + "vtvg: 1\n"
            + "sjrz: 4\n"
            + "djdv: bhsd * fwpt\n"
            + "clnn: vhmg + mvhj\n"
            + "rdcr: mmwn + msqz\n"
            + "tmcv: pfts + rmpj\n"
            + "thpg: fnwv + jmvz\n"
            + "hzjr: sqfq - mbtl\n"
            + "qpbv: 10\n"
            + "ddft: 4\n"
            + "rlgp: 1\n"
            + "rjmq: 2\n"
            + "vnwr: fwqc * gtrd\n"
            + "rbdq: stnj * lhth\n"
            + "sbvg: 11\n"
            + "jdvs: 16\n"
            + "jnbq: dpqb * sldw\n"
            + "zjhs: dvps + cfnb\n"
            + "zgzf: gfwd - qztd\n"
            + "mtrd: 17\n"
            + "jlnp: vtqj * glcm\n"
            + "hqvh: 2\n"
            + "gght: bbbr * tbhz\n"
            + "fpfw: lwgl + vljp\n"
            + "flfd: 5\n"
            + "wnql: 5\n"
            + "bhsd: 5\n"
            + "qlpq: 5\n"
            + "dplf: 7\n"
            + "lnsv: 4\n"
            + "jtpp: hqqf * shdw\n"
            + "djrf: njpq + zzbn\n"
            + "nbqz: 2\n"
            + "bpgg: njqf * vrlm\n"
            + "hmzm: mmwd + mhbc\n"
            + "vpnq: 3\n"
            + "lhsw: 5\n"
            + "lnlw: 2\n"
            + "tdrq: sjvh + ldwb\n"
            + "lnlp: 7\n"
            + "pfts: 4\n"
            + "lsjr: 4\n"
            + "wfbb: zztp + nmhp\n"
            + "fqsj: 4\n"
            + "nsms: lhpf * slnp\n"
            + "szzm: tmzn + zngr\n"
            + "wjnv: 3\n"
            + "pcqm: 5\n"
            + "dvfh: 16\n"
            + "hrvz: 6\n"
            + "vwpq: 5\n"
            + "qgvq: 3\n"
            + "dfzh: 4\n"
            + "pqbz: 16\n"
            + "frjw: zvfg - mwvb\n"
            + "hrlr: 2\n"
            + "wvdp: 1\n"
            + "psst: 2\n"
            + "mgpw: sddb + cpnt\n"
            + "cqgg: ssrd - sdgl\n"
            + "lhrt: 8\n"
            + "nngz: wvtf - shfp\n"
            + "pjhq: 2\n"
            + "jrjr: 5\n"
            + "cvcs: 3\n"
            + "tfbw: 2\n"
            + "znqd: 3\n"
            + "ctmh: 2\n"
            + "ffhs: 5\n"
            + "wcht: 2\n"
            + "sjvg: wftn * lnsv\n"
            + "rfvq: 1\n"
            + "spvl: 4\n"
            + "gwsp: wmwp * rjrt\n"
            + "hzsr: qwqw / pblj\n"
            + "rzmz: hrdr * wqcw\n"
            + "dwwq: wzcd + szzm\n"
            + "svpd: 19\n"
            + "rsjn: hlbv * dmrp\n"
            + "fwfj: qvpb + tcrv\n"
            + "mzzj: 5\n"
            + "rttd: fznc - vqlp\n"
            + "fpwh: zcpw * vnrj\n"
            + "wdbb: 2\n"
            + "bbbr: 2\n"
            + "pbjd: vwrl + ljdt\n"
            + "djpj: lhsw * dgwp\n"
            + "lffl: 5\n"
            + "fpwb: 3\n"
            + "rhrj: ndjw / bgng\n"
            + "tlcq: 1\n"
            + "zlwg: 5\n"
            + "bnzd: mcft * mzjt\n"
            + "smsg: jbvl - qvln\n"
            + "ffvm: dfwh + rfvq\n"
            + "wmjv: stcb * zffp\n"
            + "fsmb: pprc * rvbt\n"
            + "cvqd: zggj + wdnr\n"
            + "gjbl: nngz * tlvc\n"
            + "ptjs: jvwt * vzmc\n"
            + "mjwc: 8\n"
            + "qztd: 3\n"
            + "rqqh: 5\n"
            + "fdfc: rglz * jzzh\n"
            + "njqf: nhsw + llrt\n"
            + "tcvd: vwwv * twnr\n"
            + "qrlj: pjsj * vghh\n"
            + "qqrj: jlrs + fjvg\n"
            + "jdcf: 16\n"
            + "rvwj: cgcm - pvgw\n"
            + "btfg: 7\n"
            + "cdfl: vbbc * qntz\n"
            + "gjgt: zqjq / tczt\n"
            + "shfj: 5\n"
            + "hdqv: 2\n"
            + "btgd: 6\n"
            + "cdzd: hgws * fwft\n"
            + "gnvf: 4\n"
            + "fdqn: 2\n"
            + "jwnt: dbwv + jzfm\n"
            + "flvg: csmf + mfrp\n"
            + "wqqz: rvsn + tfjb\n"
            + "zqmh: cjtp * bsll\n"
            + "rtcf: 2\n"
            + "mtld: 2\n"
            + "btbf: 3\n"
            + "vsjc: 3\n"
            + "vgrc: nhdd * wgqf\n"
            + "bnrc: 19\n"
            + "jrfg: 4\n"
            + "gtdq: 2\n"
            + "vrpg: 4\n"
            + "qzlc: 5\n"
            + "vfnb: 20\n"
            + "mprs: zfvv + wnzm\n"
            + "wdsp: mgdf * mtrd\n"
            + "slqz: 4\n"
            + "rpnp: 5\n"
            + "jdtn: 4\n"
            + "npqw: pchs + dplf\n"
            + "nntd: dtgm * qwvr\n"
            + "smdl: 17\n"
            + "lzwb: lrdp * cfmz\n"
            + "jdrb: jmwv * spvl\n"
            + "rdsq: 5\n"
            + "qhwt: lhff + qblz\n"
            + "nhdd: 8\n"
            + "twhf: 2\n"
            + "hzvg: 5\n"
            + "zztd: rffv - rcwg\n"
            + "gphd: bshf / csdm\n"
            + "fszw: 2\n"
            + "lnqr: 3\n"
            + "htnv: 5\n"
            + "rnfs: 11\n"
            + "fdls: 10\n"
            + "wvtf: 8\n"
            + "fdsd: 16\n"
            + "smng: 8\n"
            + "slnp: 2\n"
            + "ddhr: pslt * bvhr\n"
            + "gnbn: jrns + mvzw\n"
            + "glsn: 13\n"
            + "qbgt: ltgr * tzvb\n"
            + "vdsv: 4\n"
            + "rncw: tdzt * lzcz\n"
            + "gdbm: 2\n"
            + "vtsr: bfjg + mjhd\n"
            + "tdnq: 3\n"
            + "btql: sgzm * tjbp\n"
            + "vsfl: rcvq + dbqt\n"
            + "hwvf: mbzr + qffv\n"
            + "mjjw: 3\n"
            + "zqpf: jztp * pjwg\n"
            + "cmlw: 3\n"
            + "lrjr: 3\n"
            + "hpmw: 9\n"
            + "sgcs: thtp + ssnv\n"
            + "hsrq: 2\n"
            + "nmds: szlr * dfgg\n"
            + "wdnr: 9\n"
            + "srwd: cmhf + mlwh\n"
            + "jgdr: ldgm * qzss\n"
            + "nqcj: fcfg * nbgd\n"
            + "zmdv: 3\n"
            + "jsss: whlh * bwlt\n"
            + "zrql: nfbm * bgmt\n"
            + "twng: 9\n"
            + "qffv: rbbn * nvll\n"
            + "mrmb: chfr + jfjl\n"
            + "lmrw: 2\n"
            + "sswq: wnzj * qjfq\n"
            + "qwqw: grbh * bgbm\n"
            + "zwvq: 4\n"
            + "ggtf: vvcp + sjcb\n"
            + "gftc: 6\n"
            + "ndjw: vgrs * qhzt\n"
            + "jbms: 1\n"
            + "jvfm: sjrz + vsjc\n"
            + "djzs: srjl + wvhr\n"
            + "bfrj: 4\n"
            + "tvnm: mpsq * hwng\n"
            + "nvcm: 3\n"
            + "gtvm: 12\n"
            + "nvll: rlgn + tldr\n"
            + "cqvp: 2\n"
            + "jtpv: mjjw * msgn\n"
            + "tlls: 2\n"
            + "ggcz: 4\n"
            + "hvnn: 3\n"
            + "nvzp: 3\n"
            + "fdmz: 2\n"
            + "dbqt: bwvt * pqwl\n"
            + "bbvf: bwpm * lpjc\n"
            + "vmrp: 4\n"
            + "rvjz: rvwj + nqcj\n"
            + "wvgb: dzfh * tvnm\n"
            + "fzlc: 5\n"
            + "sgnq: 2\n"
            + "wqcw: 2\n"
            + "dwpf: rtcf * bgbg\n"
            + "zvsv: jrmw + bjrg\n"
            + "pjjl: 5\n"
            + "ldgm: 2\n"
            + "dwdv: 3\n"
            + "dzgq: 3\n"
            + "szcm: 2\n"
            + "frbq: pwmb + dfgr\n"
            + "qgjv: 2\n"
            + "nnrm: hfgq * tvgb\n"
            + "rmds: gczl * chch\n"
            + "dgjd: jwbz + rzmv\n"
            + "sqpz: 4\n"
            + "bvvs: wwhn - ndmb\n"
            + "tdzr: mbnh * cfhb\n"
            + "qtds: 2\n"
            + "schl: tcmc + llct\n"
            + "qblz: fsvr + hrvz\n"
            + "wnfl: 7\n"
            + "lhbv: 2\n"
            + "jlbc: 5\n"
            + "ztmr: 1\n"
            + "blcp: 4\n"
            + "zmlm: 2\n"
            + "jnjq: qgpz * fdhm\n"
            + "dtpj: qnzp * mbfw\n"
            + "ttjf: wfqg - rcmp\n"
            + "jwpf: 3\n"
            + "vbpl: 5\n"
            + "fhqs: dlwf * tqcc\n"
            + "stbc: bzgg * gfcq\n"
            + "hsgz: mbjf * grhf\n"
            + "tnbt: ssfv * sglf\n"
            + "tgtn: clhr * lpwb\n"
            + "fdhm: 2\n"
            + "pqbm: 4\n"
            + "wwhn: npqw * mwcn\n"
            + "wrwl: 2\n"
            + "bgdn: 8\n"
            + "dbwv: zqfn * mqjh\n"
            + "zrpf: 2\n"
            + "mpwf: fwph + ggtf\n"
            + "nssv: 2\n"
            + "hdcq: cvgg + hqwh\n"
            + "dcvd: 2\n"
            + "vzfr: 3\n"
            + "pqnq: 1\n"
            + "bwtn: hljs + tdzr\n"
            + "bdml: npbb + cmbz\n"
            + "stcb: scnp * tlfz\n"
            + "dlbm: 7\n"
            + "chfr: cttd * gscm\n"
            + "dpjg: 13\n"
            + "gmbc: mgpw + whgh\n"
            + "lzzs: 5\n"
            + "wshw: swgs * drdp\n"
            + "zsrf: 2\n"
            + "cfpc: cdtm + rdsq\n"
            + "bmrj: 14\n"
            + "qmcz: dsff * pmfb\n"
            + "qbpg: 5\n"
            + "shdw: 5\n"
            + "tdrt: 10\n"
            + "lllv: wspv + jhdj\n"
            + "grjs: dzlj - mqff\n"
            + "hdwn: 6\n"
            + "sjvh: rjrh + mlgn\n"
            + "vwrl: 5\n"
            + "jvwt: 10\n"
            + "rbjn: 10\n"
            + "mbfw: 2\n"
            + "jfhl: 5\n"
            + "mqlw: 4\n"
            + "smfs: 2\n"
            + "dpqb: srrm + fzcj\n"
            + "gmzj: rfhf * fwhd\n"
            + "mdph: 11\n"
            + "dvhf: cfpc * jwpf\n"
            + "ngdr: lzzj * rcgd\n"
            + "sznj: fzzr + mgqz\n"
            + "nbrf: tqrq / wgmg\n"
            + "nnhr: gpzm + gdjq\n"
            + "qflv: 5\n"
            + "zmzm: hrlr * tztv\n"
            + "mpvs: rcfv * qtds\n"
            + "hqqf: 2\n"
            + "hltl: 20\n"
            + "mbjf: 7\n"
            + "tjwr: cscw + rjtv\n"
            + "jpsh: 11\n"
            + "drmp: 11\n"
            + "cspq: vmqf * qwhw\n"
            + "ntqb: 2\n"
            + "bqzd: 19\n"
            + "tsvm: tqrd + jsss\n"
            + "tzbj: 7\n"
            + "rnrt: 2\n"
            + "mrgt: qqwq + qzzz\n"
            + "lpjc: 5\n"
            + "plss: 9\n"
            + "fpjd: vzfr * bjzl\n"
            + "jmhc: bpgv + djgb\n"
            + "tqtf: sfsr / vmrp\n"
            + "jrtn: 14\n"
            + "wljc: 8\n"
            + "zplt: 7\n"
            + "bvgt: tljw + flvg\n"
            + "rcmp: 15\n"
            + "snqj: bnpf * sgnq\n"
            + "rcgd: swfh + jqpr\n"
            + "qjfq: jmhc + dmwb\n"
            + "cmhf: 8\n"
            + "bvsd: 5\n"
            + "whpb: zdpt * jntf\n"
            + "dzlj: bjln / bgcc\n"
            + "rzgr: rsgc * zdpn\n"
            + "hhnh: sngr + bsbb\n"
            + "wwsp: 7\n"
            + "mbsb: hlbd * whrp\n"
            + "gbbz: smsg * hbvj\n"
            + "dzmz: tvzt * hhnh\n"
            + "hphv: 2\n"
            + "qsfc: 10\n"
            + "fmgz: lbpw * fpwb\n"
            + "jtmq: lpzp + dbbq\n"
            + "hmgg: 2\n"
            + "vwwv: 2\n"
            + "crzf: 2\n"
            + "spdl: hqms + sbwg\n"
            + "bgbg: 3\n"
            + "cfhr: 5\n"
            + "gfht: 13\n"
            + "pqwl: 8\n"
            + "sfgt: rjgl / zqmf\n"
            + "npmm: 2\n"
            + "frbf: 2\n"
            + "hmjp: lrtc * hcwj\n"
            + "dtwq: hgvb / lnms\n"
            + "djgb: pdpd / qjjm\n"
            + "jlst: 7\n"
            + "tczt: 2\n"
            + "drfb: sbsr + mpwz\n"
            + "dtnn: bccq * pcvg\n"
            + "rzft: hzvg * rstm\n"
            + "hzrw: jqcr * rqcs\n"
            + "vcdl: fpmn * jttq\n"
            + "hjhd: zhjm + sctq\n"
            + "fgtg: pvrw / fsvh\n"
            + "bsbb: 3\n"
            + "lgzw: fpfw * qbgt\n"
            + "bgtj: jjqr * zvsv\n"
            + "pmgp: 13\n"
            + "hwng: tzcm * vsht\n"
            + "slhq: mhrs + qrhw\n"
            + "whfw: 2\n"
            + "cgsm: pffc + jtrl\n"
            + "bspl: 4\n"
            + "lvdf: 2\n"
            + "qvnw: sbfp + ldcc\n"
            + "rdtm: lsls + fjst\n"
            + "lswq: 4\n"
            + "zhvl: nllb * glll\n"
            + "rzgj: wjbs * lfcp\n"
            + "njgr: 8\n"
            + "gwlj: mjmj + pwgl\n"
            + "zffp: 3\n"
            + "bccq: psgg + lqlq\n"
            + "mvjs: 4\n"
            + "wmgs: 4\n"
            + "wwcg: 1\n"
            + "tvgm: 2\n"
            + "wwnm: 5\n"
            + "jlwc: hhzd * fdvh\n"
            + "zlbs: 3\n"
            + "mrrv: 4\n"
            + "jpdt: wmjv + dzmz\n"
            + "wvhr: fppp * svqz\n"
            + "dmvf: prlg + znvq\n"
            + "dcjg: 13\n"
            + "tndw: 7\n"
            + "qdff: qfdp * ccbz\n"
            + "zmzn: 2\n"
            + "zjvp: mtpv + zvqj\n"
            + "phpr: lcwn * jsrm\n"
            + "pmcp: 6\n"
            + "qswg: 11\n"
            + "gczl: wfbq + cdfl\n"
            + "grmd: bhlf / jcmr\n"
            + "fjqw: 5\n"
            + "pvmn: vsvz + sqnn\n"
            + "ljdt: 18\n"
            + "vtmz: vmnh + wjtn\n"
            + "tnnn: qzwp - rczj\n"
            + "nqzp: lthv + bwwd\n"
            + "brnl: sqlh + plsr\n"
            + "wbgd: wjmn * jgdr\n"
            + "cscw: jzlz * qsng\n"
            + "cpmq: 3\n"
            + "bzsl: mjbb * gvsm\n"
            + "qjqm: jfpm * hqbh\n"
            + "rjgt: pgtf * cndb\n"
            + "whgm: 4\n"
            + "rnpn: 2\n"
            + "ssfv: ptjs + btdf\n"
            + "tvzt: 5\n"
            + "qcdj: 10\n"
            + "hbsh: 8\n"
            + "clzz: lgzl * pjdm\n"
            + "pptp: ffhs + rzgj\n"
            + "brdg: zfgl + bztb\n"
            + "pslt: rqrz * mjjf\n"
            + "mccw: 5\n"
            + "tjgd: tqzr - bbvj\n"
            + "fbvn: vwhg + flfd\n"
            + "szzj: 2\n"
            + "zgcs: 2\n"
            + "cdpt: 6\n"
            + "hqff: 3\n"
            + "rjtv: llsp + ljbs\n"
            + "dvsw: 3\n"
            + "rncc: fvqv * dlbm\n"
            + "fszz: bcdw + brnl\n"
            + "clzs: rdsh * mvjs\n"
            + "jmwv: 2\n"
            + "rqqr: 9\n"
            + "lgzl: 2\n"
            + "lbjz: 3\n"
            + "ghzh: 2\n"
            + "tlvc: 3\n"
            + "vbqv: jwnt + fpjd\n"
            + "mngm: 19\n"
            + "frqw: 2\n"
            + "qgpz: rjgt - drhg\n"
            + "vrjr: jbms + wqqz\n"
            + "fqhb: tfgf + zvrh\n"
            + "rjrt: mdph + fqtv\n"
            + "qwmz: 7\n"
            + "qzmg: nbrl * qnsw\n"
            + "fczh: 2\n"
            + "wsnh: 4\n"
            + "jmvz: lpgm * fszw\n"
            + "sjfd: lrjr * jrfg\n"
            + "fsld: rjms + rfgl\n"
            + "flbg: 6\n"
            + "mpwz: lmhf * sspm\n"
            + "rstm: 5\n"
            + "cqtm: ljrh * wbgd\n"
            + "glmn: bvgt * bmcl\n"
            + "dbhn: 3\n"
            + "fhdt: 5\n"
            + "ltsl: phnr + jnjq\n"
            + "zqmf: 2\n"
            + "fdvh: 2\n"
            + "pjnb: 7\n"
            + "pvgw: 5\n"
            + "tlfz: 3\n"
            + "qfhl: 16\n"
            + "sfsr: ngdr * wlcw\n"
            + "sngr: 20\n"
            + "qzwp: jfsw * qcpv\n"
            + "tfzj: wshw + vcdh\n"
            + "fmwm: 5\n"
            + "swhr: gspg * sfgt\n"
            + "qqht: frjw * cvcs\n"
            + "nszh: 4\n"
            + "fcnp: 5\n"
            + "tbhz: qntd - szzj\n"
            + "qmcs: phpr / hdqv\n"
            + "nbbh: btnz * nvgb\n"
            + "bjln: btvt + bbrg\n"
            + "fpvq: 5\n"
            + "ltwg: 2\n"
            + "cjgq: 2\n"
            + "lcwn: 2\n"
            + "cjbm: 20\n"
            + "vttc: 16\n"
            + "bjwf: 1\n"
            + "mjmj: nwqc / hsgf\n"
            + "hznh: 3\n"
            + "wssz: gmbc * rzsp\n"
            + "fmvp: 16\n"
            + "vtqj: mvtb + gnvf\n"
            + "vclb: 3\n"
            + "hnhv: 6\n"
            + "bnpf: 11\n"
            + "nvmt: pfpq - dpbc\n"
            + "fgcs: bpgg * swzv\n"
            + "lbvn: 2\n"
            + "ggzt: 14\n"
            + "tqzd: plhm + hlhf\n"
            + "hnng: pvdj + qwlc\n"
            + "sbfp: swcf * qjqm\n"
            + "cmfn: 8\n"
            + "pjdc: 2\n"
            + "bcld: jlnp + gmzj\n"
            + "pbtm: hlhb * vqht\n"
            + "pnfv: 2\n"
            + "rfgl: srnp + vdtv\n"
            + "jnvz: lzms + vzhf\n"
            + "rsvl: gncz * shfj\n"
            + "pqcv: 3\n"
            + "cjtp: 2\n"
            + "cttd: 5\n"
            + "rfhf: 5\n"
            + "lsfz: ghzh * jrnz\n"
            + "llrt: 2\n"
            + "fcpr: 6\n"
            + "zjdf: rmpm * bghj\n"
            + "qfqp: wdjn + rsjn\n"
            + "qwbz: mjwc + zhvs\n"
            + "dctj: 3\n"
            + "fljq: hjnj * tcjf\n"
            + "hqwh: vdqh * tmqr\n"
            + "pjmv: dlsn + vftg\n"
            + "hgjz: 4\n"
            + "bfbg: 4\n"
            + "wvjz: vsjp + nsms\n"
            + "tzvb: 3\n"
            + "sdgr: fhlf * rnrt\n"
            + "jfmf: 3\n"
            + "lrdp: 11\n"
            + "jztf: 5\n"
            + "wzrd: pwwm + dchl\n"
            + "wftn: 2\n"
            + "fbwt: mclf * zztd\n"
            + "prqs: wjnv * dbjv\n"
            + "mhjw: hzjc * gcjw\n"
            + "mvpt: 17\n"
            + "nsrh: 3\n"
            + "vnzp: 2\n"
            + "hjnj: 5\n"
            + "qnsw: zcdn + spgm\n"
            + "pshf: 2\n"
            + "zlrm: nhcg + bnnl\n"
            + "blhv: 2\n"
            + "sngl: llqs - zmzn\n"
            + "nnzq: dlqm * dpjg\n"
            + "ngwq: cdzd + ghlb\n"
            + "zrdh: 2\n"
            + "ljbs: 1\n"
            + "ldcc: zmmw * lvpz\n"
            + "pwwd: 3\n"
            + "smpd: zrpf + thpg\n"
            + "bjrp: 10\n"
            + "dnmd: rfcn / qmtv\n"
            + "trld: qtnr * lsqn\n"
            + "ptng: pgml * fpjw\n"
            + "lvsg: 2\n"
            + "pzmw: 9\n"
            + "gsnc: 2\n"
            + "gbqg: 2\n"
            + "mttg: wvgm - drfb\n"
            + "nmtm: 5\n"
            + "bgng: 5\n"
            + "nnww: smdl * lpqf\n"
            + "tjnz: mspm * pnfv\n"
            + "vqwj: 2\n"
            + "dmss: hbsh + zhcg\n"
            + "qjdm: stvp * vmrs\n"
            + "trgr: czcc * glsn\n"
            + "mjjf: pmcp + fnst\n"
            + "qnzp: 4\n"
            + "npvj: 4\n"
            + "vrgt: 3\n"
            + "grbh: lhbv + sdvl\n"
            + "shfp: 1\n"
            + "nhmj: 19\n"
            + "mcgc: 3\n"
            + "dzfh: vczn * fhdt\n"
            + "tcrv: gpjv - nfpw\n"
            + "gmtw: ghts + vhcp\n"
            + "dtgm: 2\n"
            + "gjnm: 2\n"
            + "nmhf: hfhs * mhjw\n"
            + "bgcc: 2\n"
            + "wfqg: ptqr * ttdj\n"
            + "scnp: 3\n"
            + "llnp: nqfh * cmgn\n"
            + "vlhr: fnwh * dcpz\n"
            + "gdvv: 18\n"
            + "jqhz: hqgn + fbvn\n"
            + "sjsv: cmgv * llfp\n"
            + "cnsq: zdpc + jpdt\n"
            + "cpnt: 17\n"
            + "qlqd: qvsh * rscq\n"
            + "sgpw: hsdv + fljq\n"
            + "cvlv: 3\n"
            + "zvtf: tllt * tfcf\n"
            + "mtvg: vrtf + mrzl\n"
            + "fsfp: 13\n"
            + "zdpt: 10\n"
            + "mlqr: 5\n"
            + "wwvg: 10\n"
            + "swcf: 5\n"
            + "fpnv: 4\n"
            + "vfbz: 2\n"
            + "zcgl: 2\n"
            + "fgnf: 1\n"
            + "vnbc: qgmn * zhpj\n"
            + "zqhm: 20\n"
            + "nqvr: 5\n"
            + "hfvl: 2\n"
            + "fmmh: 4\n"
            + "pdqd: 1\n"
            + "zfpc: 4\n"
            + "drhv: mmqp * hrff\n"
            + "pjfq: qwqr + cjwt\n"
            + "hhdw: ppnq + slqz\n"
            + "zvfg: 9\n"
            + "mzml: 2\n"
            + "zrpb: pqjn * lwvv\n"
            + "rwpc: bgdn * jrtn\n"
            + "qwvr: bhvm + gpwl\n"
            + "vlmc: sftz * gmdd\n"
            + "nwzb: 2\n"
            + "swzc: sqhp - pzng\n"
            + "sddq: jvfm * zjdf\n"
            + "ctmz: 20\n"
            + "nbjw: 2\n"
            + "phfm: zsrp + tsws\n"
            + "rjpv: lmrw * dbdf\n"
            + "qnqh: 5\n"
            + "rhvv: gzpp + vlzv\n"
            + "vsll: jmld - qpvs\n"
            + "mqrh: qrnn + mczq\n"
            + "swgc: wbjq * fmvp\n"
            + "tzcm: 3\n"
            + "jqdh: fpbm + crfg\n"
            + "jzwl: szcm * rzbr\n"
            + "pdpw: blhv * pvbv\n"
            + "tqmf: swhr / mwjf\n"
            + "nbfv: 2\n"
            + "rfcn: lwvj + gbbz\n"
            + "vgrn: vlhr + bcsf\n"
            + "pvrw: rqwr + jhgj\n"
            + "wqql: vdgt + hgfc\n"
            + "ptjj: nvqv * vdvn\n"
            + "sswr: gbjs * cpbb\n"
            + "vgrp: 5\n"
            + "tbgb: dgjd + nvfn\n"
            + "nppr: mtvg * cvqd\n"
            + "bcsf: 11\n"
            + "gpmm: zgzf * rsmp\n"
            + "swcd: 3\n"
            + "mmqp: snpf * ltwg\n"
            + "wjtn: 2\n"
            + "vhcp: lfnl * mjlf\n"
            + "wrms: hlrv + dgzd\n"
            + "rffv: 9\n"
            + "hrvm: 4\n"
            + "sctq: jrdb * llnp\n"
            + "ljcq: 3\n"
            + "dmjv: pzgm + bjwf\n"
            + "jrmw: tmwv + vrmz\n"
            + "rcfv: 5\n"
            + "rhwf: 2\n"
            + "cjwt: 1\n"
            + "btdf: hztc / scjs\n"
            + "bnnl: vcdl + rbjn\n"
            + "lpzp: rbdq + fjtr\n"
            + "ttdj: 8\n"
            + "bvcg: 5\n"
            + "mhbc: 3\n"
            + "lhcr: 3\n"
            + "rcrc: rdcr * tzbj\n"
            + "mglm: 2\n"
            + "bwww: pjhg * jnrp\n"
            + "dqgm: hznh * mhnr\n"
            + "root: fgtg + pbtm\n"
            + "dpbc: 10\n"
            + "jnlr: 1\n"
            + "lfcp: 3\n"
            + "rgsw: wwsp + zclh\n"
            + "zdpn: 7\n"
            + "pffc: sswq + mwbj\n"
            + "ghcc: bzsl + phfm\n"
            + "nzbp: 3\n"
            + "lwvj: ggcz * sqrm\n"
            + "chhv: 2\n"
            + "rlfm: 3\n"
            + "bbrg: dtnn / mmnq\n"
            + "qrhw: ljjw + sbvg\n"
            + "mzzb: 13\n"
            + "zmmw: fppn + lmhj\n"
            + "mczq: jtpp - vsql\n"
            + "hqbh: 3\n"
            + "nhjz: 5\n"
            + "fpbm: hrhw * lztm\n"
            + "vwhg: dzgq * fllw\n"
            + "bvhr: wsnh * qqds\n"
            + "grhf: 5\n"
            + "rvbt: mzml * gtpv\n"
            + "hljs: bmrj * vczt\n"
            + "hdhf: zjhs * fdqn\n"
            + "qqds: vmtm + gmsv\n"
            + "tfcf: 4\n"
            + "jsbv: 2\n"
            + "sglf: 2\n"
            + "jmld: psrv / htnv\n"
            + "mmnq: 2\n"
            + "gqzs: vlmc + zfnv\n"
            + "znvq: tnhm * vwpq\n"
            + "dcnc: hzjr + hcps\n"
            + "fjbm: vnbc + hdcq\n"
            + "zhjm: 11\n"
            + "wfrh: djdv * jtfh\n"
            + "whnb: tbqf * qdmq\n"
            + "mtgv: tqbd + qdfc\n"
            + "rzbr: hvpp + nwzb\n"
            + "rsmp: wtmp + fczh\n"
            + "fwft: gwlj * vnzp\n"
            + "nfsr: fnbg * cwwf\n"
            + "spsp: 2\n"
            + "nvqv: 2\n"
            + "nqfh: 3\n"
            + "mqmn: bcns * prrh\n"
            + "szgq: 3\n"
            + "lqng: rdgc - whzr\n"
            + "cpzc: 2\n"
            + "stnp: 9\n"
            + "hgsz: qfzw * tjnz\n"
            + "bjzl: 18\n"
            + "mcjw: gtqq * ljst\n"
            + "fvjn: wvjz * znqd\n"
            + "njpq: fgcs + smtv\n"
            + "lvdn: dnqm + slhl\n"
            + "qzss: 4\n"
            + "ffrp: 4\n"
            + "qzjh: 3\n"
            + "lrtv: fzcp - dtdq\n"
            + "bfht: ttjf + qbbm\n"
            + "hlbv: qcqc * dtwq\n"
            + "nvgb: rmzz + nlsv\n"
            + "llqs: 12\n"
            + "whgh: 8\n"
            + "tvgb: 17\n"
            + "tbrb: bdml - zvhb\n"
            + "thmh: snqj + tbcp\n"
            + "gmjr: hdwn * wtcl\n"
            + "stln: vslv * bfbj\n"
            + "hsgf: 7\n"
            + "bpts: pwwd * pvmn\n"
            + "tnhm: 5\n"
            + "hptd: gddp + nspv\n"
            + "htrl: 5\n"
            + "gfwd: btfg * nprr\n"
            + "cqpp: mlpg + wqgb\n"
            + "fsmj: 5\n"
            + "ldwb: lvsg * qftc\n"
            + "mrqj: gmtw / sjvg\n"
            + "vsjp: wfrh + mhqm\n"
            + "lhpf: nntd + cvcl\n"
            + "qllt: 3\n"
            + "hqwm: bttt + qwmm\n"
            + "mwbj: clnn * vhpz\n"
            + "wvlj: 2\n"
            + "zvrl: grjs * rtsj\n"
            + "dpwh: gfzq + mftb\n"
            + "tllt: ntps + phlz\n"
            + "grwm: hqwm * wgcl\n"
            + "jzfm: 1\n"
            + "qjjm: 2\n"
            + "vljp: 1\n"
            + "vbbc: 5\n"
            + "mcft: nccv / psst\n"
            + "lhff: 14\n"
            + "wspv: mzdr + fpww\n"
            + "fssw: mbqq * wsng\n"
            + "mqjh: zfpc * lncr\n"
            + "lccm: 2\n"
            + "vppj: dfzh + dvsw\n"
            + "hvpp: lvdn - whmz\n"
            + "hbgz: 1\n"
            + "mclf: ptjj / lhrt\n"
            + "jqcb: 19\n"
            + "cbtc: 2\n"
            + "zclh: 6\n"
            + "jnct: rmrr + sddq\n"
            + "cwdv: wvgb + ddhr\n"
            + "stnj: qwpv - vgrr\n"
            + "wtgm: 11\n"
            + "lvdq: 2\n"
            + "jztp: 9\n"
            + "nplp: vgrn * gprv\n"
            + "qssh: 5\n"
            + "fwpt: mbsb + jgwm\n"
            + "sqnn: fgwt - ggvp\n"
            + "phlz: mwlp * mpbl\n"
            + "jbcv: 19\n"
            + "cmgv: hjzq / jsbv\n"
            + "bnnn: 5\n"
            + "vgrz: zqhm * hrvm\n"
            + "fzcj: 1\n"
            + "sbsr: 2\n"
            + "mgrl: 2\n"
            + "vffw: 2\n"
            + "wzcd: 1\n"
            + "lzds: fwfj * zcws\n"
            + "tlgc: 2\n"
            + "pwnv: 3\n"
            + "cdvz: 2\n"
            + "fzcs: tdwg / hpdf\n"
            + "cblr: tdsz * rtsq\n"
            + "dtzd: 4\n"
            + "wfnp: tnbt / jphh\n"
            + "jbvl: gwwv / fdmz\n"
            + "wsng: 2\n"
            + "glpr: 7\n"
            + "rhqd: wtsv - gjcc\n"
            + "mgdf: lsfz + brrj\n"
            + "cvcl: tbrb + mhlb\n"
            + "gjcc: 5\n"
            + "mqjq: 4\n"
            + "fvmw: mqbl + fvjn\n"
            + "pjwg: fzlh + ssgv\n"
            + "bwpm: 5\n"
            + "fflz: 2\n"
            + "sslm: 12\n"
            + "blls: 3\n"
            + "zrms: cqvp * mvpt\n"
            + "lmhf: 3\n"
            + "tdsz: 6\n"
            + "nnvq: sltp * smfs\n"
            + "lfgl: 2\n"
            + "hhzd: 7\n"
            + "crfg: nvmt + zrms\n"
            + "hvbm: gdtg * wghj\n"
            + "rjlv: 3\n"
            + "pwwm: mtfz + bpts\n"
            + "rzmv: cvcq * jjqv\n"
            + "mgcr: 8\n"
            + "mlgn: jstl / rnpn\n"
            + "ptqr: nhjz + gpfh\n"
            + "drdp: tvjf + bcld\n"
            + "dstt: nthp * ntts\n"
            + "qtvv: jrzz + dwwq\n"
            + "zhcg: 5\n"
            + "gddp: lwqf + tsvm\n"
            + "jcmr: 9\n"
            + "fjst: gqnr * tfng\n"
            + "mlvg: bdrg / mgrl\n"
            + "nlsv: 2\n"
            + "vmnh: ggzt / cmww\n"
            + "bnfl: ddrd + jffd\n"
            + "bwpt: pjnb * gtws\n"
            + "lqss: zztm * rvpv\n"
            + "fzqg: vffw * tbvv\n"
            + "gwvt: 7\n"
            + "bsll: tdnq * hjnb\n"
            + "thhz: 5\n"
            + "cfmz: 5\n"
            + "bfjg: 2\n"
            + "zfnv: hlnh * fjfm\n"
            + "rjms: glpr * tvgm\n"
            + "fllw: 2\n"
            + "nfbm: 2\n"
            + "hnwt: jrjr + trgr\n"
            + "wdvc: 2\n"
            + "bjlm: 3\n"
            + "ssgv: 3\n"
            + "cwwf: 5\n"
            + "fppp: 7\n"
            + "lbpw: 7\n"
            + "qftc: lqml + nfbv\n"
            + "bfbj: pgqn / tvrz\n"
            + "lbfp: 3\n"
            + "qstq: 2\n"
            + "jffd: gnbn / lnlw\n"
            + "cvcq: pjmv * mcgc\n"
            + "mzjt: 2\n"
            + "mbvs: 2\n"
            + "szlr: 2\n"
            + "zzpp: 2\n"
            + "tmzn: pjnn - lbvn\n"
            + "gfbm: 2\n"
            + "bdhm: 2\n"
            + "wvbp: 3\n"
            + "rczj: prqs * jsmg\n"
            + "nvtp: 2\n"
            + "tfjb: 1\n"
            + "tfng: 8\n"
            + "zvfv: 3\n"
            + "rldj: sjst * zplt\n"
            + "lpwb: qfqp * frqw\n"
            + "tqcc: 8\n"
            + "jfwp: 2\n"
            + "mmmz: ssst * sdmw\n"
            + "sjcc: 11\n"
            + "srcq: 6\n"
            + "nhmp: 3\n"
            + "whzr: 2\n"
            + "ndhj: pwnv * rswf\n"
            + "wjmn: 3\n"
            + "qcqc: 2\n"
            + "qqgz: 3\n"
            + "cgqq: mqmn + zrql\n"
            + "jvjc: 7\n"
            + "hmbb: 10\n"
            + "tjbp: 2\n"
            + "whlh: 9\n"
            + "jqbn: fssw - stln\n"
            + "fqcq: qrlj + wsfz\n"
            + "plsr: fpnv * slhq\n"
            + "gtpv: jfwp * zvjs\n"
            + "jbsv: 4\n"
            + "bdlq: qjdm / fgdp\n"
            + "pdrs: 2\n"
            + "dfwh: dwpf * gqjl\n"
            + "mftb: rwpq * gmsq\n"
            + "rjgl: qbmj * pmzl\n"
            + "pffh: fbnt * cmfn\n"
            + "hgml: 2\n"
            + "sqrm: hltl + cgfc\n"
            + "qvsh: zqmh - mlqr\n"
            + "whmz: 2\n"
            + "hffl: sbnm * jnct\n"
            + "hrhw: 11\n"
            + "fgwt: nhmj + hsfn\n"
            + "twhc: 6\n"
            + "bhvm: vgrc * qfhl\n"
            + "bfvw: qzwc - stbc\n"
            + "vzmc: 4\n"
            + "hfpc: rjlv * vclb\n"
            + "hlbd: 3\n"
            + "ltgr: 4\n"
            + "gfvg: 4\n"
            + "tbcp: 1\n"
            + "ppmg: 7\n"
            + "hlrv: hzjf * thhz\n"
            + "ghdc: 17\n"
            + "lcdp: fwtq * cffj\n"
            + "qsng: cqhh * chhv\n"
            + "qmmz: mrrv + qlmn\n"
            + "btvt: grmd + rncw\n"
            + "htnp: vbpl * frbq\n"
            + "dqbf: wwwb * nbqz\n"
            + "sflg: sfjb * dtzd\n"
            + "rnnb: 5\n"
            + "wzhb: 2\n"
            + "smzc: 9\n"
            + "qmtv: 3\n"
            + "lmbh: 2\n"
            + "cdgc: 2\n"
            + "bgmt: jdns + fhqs\n"
            + "tvjf: wbfd * tfbw\n"
            + "dfgg: lscz + vdsv\n"
            + "qlvd: 4\n"
            + "gdlw: 1\n"
            + "vmrd: 7\n"
            + "pwgl: jtmq - lfzr\n"
            + "wltb: 4\n"
            + "pdpd: fzqn * npvj\n"
            + "nhcg: fjsr - qcjh\n"
            + "gfcq: ttpl - zgnb\n"
            + "npmn: 2\n"
            + "srnp: dqgm * dndp\n"
            + "bgvw: zbvc * fzlc\n"
            + "qcgv: 10\n"
            + "qqwq: jdrb - pqnq\n"
            + "qpph: 2\n"
            + "qvln: ccsb + srtc\n"
            + "rvfq: 15\n"
            + "pvbv: 3\n"
            + "zlzs: dpwh * tvss\n"
            + "tljw: hjjg * vsll\n"
            + "dqpn: zvrl - trrg\n"
            + "ldmj: 2\n"
            + "lncr: 2\n"
            + "zsqv: lzds - svqt\n"
            + "bhnt: 3\n"
            + "jrnz: wtrj / wlgz\n"
            + "hcps: wvlj * pqbz\n"
            + "fpmn: 2\n"
            + "wbtj: 5\n"
            + "tcgr: mwmn * hmzm\n"
            + "vsql: 3\n"
            + "mlpg: 19\n"
            + "zztm: 2\n"
            + "mnlm: dnps - sjsv\n"
            + "gprv: pdpw * vbgr\n"
            + "gtrd: 2\n"
            + "lvjv: qmmz + dnnc\n"
            + "mtfz: fmwm * mttg\n"
            + "cffj: 3\n"
            + "sddb: 5\n"
            + "dgjt: hgvv + lphb\n"
            + "lwdc: 2\n"
            + "fsvh: 2\n"
            + "lqlq: 14\n"
            + "hztc: lcnr * nhnr\n"
            + "ssrp: brdg * rsrp\n"
            + "pnjm: 6\n"
            + "hgfc: ggjp * mvwq\n"
            + "dbdf: 10\n"
            + "jqgb: 17\n"
            + "drhf: zwvq * nlgh\n"
            + "mtwb: qssh * fcvt\n"
            + "qcpv: qvhr + zlzs\n"
            + "dlsn: 5\n"
            + "rsrp: 5\n"
            + "wwwb: mnmz + ptsv\n"
            + "rvpv: 5\n"
            + "grcw: hpmw * twrz\n"
            + "dvqb: hwvf + ndhj\n"
            + "wbjq: sdsp + rpnp\n"
            + "rbbn: 3\n"
            + "zctw: tjzf * nrzl\n"
            + "bgbm: njgr * cpzc\n"
            + "wtsv: mzzj * jgss\n"
            + "jwdd: lhcr * djzs\n"
            + "jstl: lllv + lfjs\n"
            + "dssn: 7\n"
            + "hqgn: 2\n"
            + "mpbl: cqjn * gdnm\n"
            + "smtv: tqzd * fjtt\n"
            + "nzhg: mdgb * lzcr\n"
            + "srhw: 6\n"
            + "dblz: sdjg + gvmc\n"
            + "rjsw: 2\n"
            + "zzbn: wlsr + fsmb\n"
            + "wtrj: rtlh * lfgl\n"
            + "gvsm: 3\n"
            + "jgsl: blls * fcpr\n"
            + "lmjt: hmwv * jbzw\n"
            + "lppg: 2\n"
            + "lfjs: 4\n"
            + "lwdd: 4\n"
            + "wwgv: cjbm + btbf\n"
            + "qcpl: lfcv + hzsr\n"
            + "vttj: spsp * ngwq\n"
            + "vpzl: 16\n"
            + "nvls: mqlw + hnng\n"
            + "phpm: nvzp * vrgt\n"
            + "nthp: 2\n"
            + "tcmc: 4\n"
            + "fwph: 2\n"
            + "lnvw: lnqw * bfsr\n"
            + "wvbv: jnbq + cnfz\n"
            + "hwjg: bgjv + dqmz\n"
            + "wnzm: 1\n"
            + "nwqc: vppj * mdlb\n"
            + "mvtb: 4\n"
            + "jphh: 2\n"
            + "mhnr: 3\n"
            + "zvjs: pnjm + dmjv\n"
            + "gslg: 7\n"
            + "jbzp: 2\n"
            + "jzbt: dqpn / lqng\n"
            + "gqcp: lnqr * vpnq\n"
            + "hgvv: gbqg * lvng\n"
            + "hlhb: whnb + nqzp\n"
            + "nhsw: 5\n"
            + "zcws: sznj + jzbt\n"
            + "fghj: 13\n"
            + "rpwt: wfnp * mhtt\n"
            + "mjhd: zlbs * rwft\n"
            + "gtwh: 4\n"
            + "dgzv: thmh * jrgf\n"
            + "rglw: bhnt * nssv\n"
            + "qcrz: qpbv - lnrm\n"
            + "vdqh: 9\n"
            + "hfgq: 6\n"
            + "sdsp: 1\n"
            + "ffqb: 2\n"
            + "jttq: 13\n"
            + "zqjq: nwwl * ztlg\n"
            + "tcjf: 7\n"
            + "cnvt: jvjc * qfpp\n"
            + "znjj: bnfl / nhmp\n"
            + "nlds: vjgm + nvls\n"
            + "rlmb: bzgd + cblr\n"
            + "fwhd: 11\n"
            + "vqlp: 10\n"
            + "gpvh: 3\n"
            + "fjfm: fcbw + wwvg\n"
            + "nprr: 2\n"
            + "fpjw: 5\n"
            + "blwq: 4\n"
            + "wnlm: fmmh * pshf\n"
            + "hlhf: bvvs / tglq\n"
            + "pzng: 1\n"
            + "wfbq: ssrp + nvdr\n"
            + "cgfc: hnhv + hhlj\n"
            + "mvcg: 2\n"
            + "sqlh: srwd * npmn\n"
            + "jfcb: wtgm + wnlm\n"
            + "rqnw: hmbb + pvfj\n"
            + "wlsr: rlrl * wwgv\n"
            + "vgrs: 5\n"
            + "lqnv: wcht * jbsv\n"
            + "fvqv: dvfr * zrpb\n"
            + "gncz: tvjw * grjp\n"
            + "mrzl: lvjv / wvbp\n"
            + "sqhp: 12\n"
            + "qlmn: lgtm + ptng\n"
            + "jjqv: 5\n"
            + "phnr: lzwb * phct\n"
            + "jqpr: lbns * zlrm\n"
            + "nzlq: fcgn * fsfp\n"
            + "pjnn: cdcs + wtjn\n"
            + "cdfd: 3\n"
            + "sdmc: gsnc * tjgd\n"
            + "tjzb: ftws - vnwr\n"
            + "wwwg: 3\n"
            + "rvsn: wwcg + smpd\n"
            + "hlnh: rncc + qmcz\n"
            + "llfr: 12\n"
            + "qrzd: dqbf / gfbm\n"
            + "lmhj: 4\n"
            + "wvgm: ldmj * cbww\n"
            + "dqmz: wfbb + zhnq\n"
            + "dndp: pgvc * hsrq\n"
            + "ztlg: 2\n"
            + "lmhb: qqcj + pdqd\n"
            + "vbfp: hwhm * hwjg\n"
            + "bdrz: 3\n"
            + "sfjb: zzpp * lnlp\n"
            + "dmrp: 2\n"
            + "qwmm: 4\n"
            + "hzjf: 5\n"
            + "vjbq: 8\n"
            + "gwwq: mglm * mfdh\n"
            + "pfnq: 4\n"
            + "pcgq: 2\n"
            + "rqrz: 10\n"
            + "qwlc: 7\n"
            + "cvsb: 3\n"
            + "mdlb: rcrc / nzjl\n"
            + "tsws: htrl * zgcs\n"
            + "lnms: btgd + hbgz\n"
            + "rmrr: szgq * rhvv\n"
            + "jsmg: 2\n"
            + "gmdd: qcpl * wwwg\n"
            + "zvrd: qrzc * gtvm\n"
            + "lcgc: 3\n"
            + "tmwv: 3\n"
            + "tzhr: vpzl - jztf\n"
            + "lhth: znlp + mpvs\n"
            + "tqrd: cdgc * lzzs\n"
            + "mhqm: gbtz + nplp\n"
            + "pgvc: 4\n"
            + "vgrr: flbg + fjqw\n"
            + "zvrh: 12\n"
            + "zqmg: hptd + sjfd\n"
            + "rjrh: sngl * whgm\n"
            + "wwdw: hvbm + jlwc\n"
            + "llsp: pbjd + hjhd\n"
            + "lzzj: 2\n"
            + "gdwf: 6\n"
            + "hfhj: fdqw * qjwn\n"
            + "bwvt: trfn * hphv\n"
            + "ccbz: 4\n"
            + "zbfv: hmpv * cgsm\n"
            + "tvss: hqff * lhzf\n"
            + "jlrs: vtsr * wzhb\n"
            + "wnst: sgpw + fcll\n"
            + "jbzw: svpd + trld\n"
            + "qcbb: rwln * swzc\n"
            + "hwhm: 2\n"
            + "hrgr: 9\n"
            + "wdjn: 3\n"
            + "mqff: 1\n"
            + "hdrv: lqvd * hcbm\n"
            + "vslv: 9\n"
            + "vjgm: 8\n"
            + "zfgl: mljq + vdtn\n"
            + "mtpv: mqrh + ncdq\n"
            + "llct: 2\n"
            + "fppn: 3\n"
            + "cvgg: 1\n"
            + "jqcr: qnqh * tzhr\n"
            + "ccsb: wrwl * zqpr\n"
            + "nfpw: 1";
}
