package day03;

public class Day03Task1 {
    public static void main(String[] args) {
        int failScore = 0;
        for (String rucksack : input.split("\n")) {
            int compartmentEntries = rucksack.length() / 2;
            String firstCompartment = rucksack.substring(0, compartmentEntries);
            String secondCompartment = rucksack.substring(compartmentEntries);
            char failed = 0;
            for (char c : firstCompartment.toCharArray()) {
                if (secondCompartment.indexOf(c) >= 0) {
                    failed = c;
                    break;
                }
            }
            int failScoreHere = failed >= 'a' && failed <= 'z' ? failed - 'a' + 1 : failed - 'A' + 27;
            failScore += failScoreHere;
        }
        System.out.println(failScore);

        int badgeScore = 0;
        String[] in = input.split("\n");
        for (int i = 0; i < in.length / 3; i++) {
            String rucksackOne = in[i * 3];
            String rucksackTwo = in[i * 3 + 1];
            String rucksackThree = in[i * 3 + 2];

            char badge = 0;
            for (char c : rucksackOne.toCharArray()) {
                if (rucksackTwo.indexOf(c) >= 0 && rucksackThree.indexOf(c) >= 0) {
                    badge = c;
                    break;
                }
            }
            if (badge == 0) {
                throw new IllegalArgumentException();
            }
            int badgeScoreHere = badge >= 'a' && badge <= 'z' ? badge - 'a' + 1 : badge - 'A' + 27;
            badgeScore += badgeScoreHere;
        }
        System.out.println(badgeScore);
    }

    private static final String input = "JppMDcJPcQbqGqFb\n"
            + "ZStgnHtsSjGBhqFbBmsm\n"
            + "djzzwgHHggdnfwjtMPDPMGpPlNfpLDll\n"
            + "dRCtwtlCSttPtlNPNtgvPrDqmBsjGSpjBBsJsqqmrp\n"
            + "ZhWnZhzMMfnWWTDzBrmsmjsBccJB\n"
            + "TFQMrZrMfZrLZZnLQdlvNdCgdHPlCllHNF\n"
            + "PVddPnZWDDPqmHZzqVPzqdHdMRMJjQtvmvjvtTQQtlRtbbQl\n"
            + "fsNswFpChpNwfgtMvCbjTRJBbtRj\n"
            + "SFgfSMShLcsLgNMFhpwShFFZPHqZGZPqHdzPZHZcdzDDqd\n"
            + "dHffzCqSfJCCzCPvdcpzRrBDDBSBBBMtthDDrFMT\n"
            + "bVsZbsrgbWshBTFtDTtZTD\n"
            + "slWGNbNWgWwnmNnwgnlGjdJJdPHcvcrcHjqPzdqPvp\n"
            + "vBFBzGvGBvjFpGWcvCCvBvGPPhZbgLhMnhrPgFgPFgLLPF\n"
            + "dVlslfdJNVJJmQQwdNRNwLZZZrrqhbPbZndpdgMhLP\n"
            + "HJRHJpNJlVmftHfNQNRsHmmGCtGWjGDDTvCzcjWDStvcvT\n"
            + "cVQzCCCpVVjgHsNwwFRqSRSRRtNH\n"
            + "PWfhfPhbWWdWllPDdTvdbnvhLJLLMJFTSNwJtMRwJLqJJNMq\n"
            + "DnfblllPbDrbWmbdPFdvlhdgQzzZZzQgcpcsZGcGQQgcpr\n"
            + "hdFnnrdLnJRrZMzVlMbrwZvz\n"
            + "TgfjGCcfsqfqqBfRMPDVvVVvTZRPbP\n"
            + "qQqffcGStBSCQcsqCCBRjGqWhHFptFdnhNLmhnLWmphLLt\n"
            + "WHPqWhLWHBMqddCdtDRwStDSwgnw\n"
            + "rfCfZTmvpvvpFVfFrbvTbvcgtwgtStntggwbSJttgJtwgw\n"
            + "fpQFsmfFmfZcrFCMhWNQWLCzhhCM\n"
            + "zdqqJHDWwqNNZjQSmtdjpmfnjj\n"
            + "GFBcPfBLPThcTcLRbpTQQjpTQrjSnQjlvn\n"
            + "MFVLcsPVbPcRGfVPFRgDzJsHZNDCZNCNZsHg\n"
            + "WQdMhlmQMwfZlQdgdHfddvtzmbJbcsctbBJqqcvqzB\n"
            + "rSTrDDCSSGRCnnSGwwzJsbBvJsCCttccsvsz\n"
            + "VnFwDrNwPwVSDrLgjfZZdMQFMWgljQ\n"
            + "rJNjBLNQjvLQjFFLQJCFTvGWlRRgfGWDWlCDzlGnRRWG\n"
            + "tMMhShhwhbgplflwDlnnnzDH\n"
            + "ZcSZVMSqshhQBQqQvqQgjJ\n"
            + "btTtWGbvtcvHHccdNRhHdl\n"
            + "TDzqLPSqBzqVSldPddHhhNNlRQ\n"
            + "jBLDqDgZZBzJJmsbWjppmmpTWw\n"
            + "LLDTRRfTwZRGZfDCRTwRsVHsVFBVZVlmVFBFlFJl\n"
            + "QjWpQrzQcbhfMqrVVHVPFslFVpVmHH\n"
            + "hqhzqMfNvjvMMzhdRDdCwGDSSdnvRn\n"
            + "jmMdNCLjLmJPtHtSHhSVVJ\n"
            + "pDBqgBgCvbfGBBbCGHZhtQZtPHVSVHPV\n"
            + "pBnWgBpzWzBbWDWvzwpgCvqcmLNTrdLmmrnRLTrmrTdmLd\n"
            + "dRWWtRGBDPQctQDZ\n"
            + "CMfnCfFMmTTFVCmfmTLvsnMPZjccHRcPrRPsZQQZPQDRrQ\n"
            + "fLCffmRTCvRnmTllzVvpdpphNJggpGbJJJpdlh\n"
            + "cfsfbbWqqZqDScbhGDPDjTPmpVtmmPjPntFD\n"
            + "dCBBCRQCHNHLMQvrJJJBJLrGPMnjVtPjVMmnjPFmPmMpFn\n"
            + "HvRGLddgHHvqhwzbWhcgcf\n"
            + "DHmhhDDhbqrRhvbrHqhPbPvBwwWwTmMGTVwwBMGWVNNwVw\n"
            + "gSzJjnnjsscfcsZcSfWwQGdMMcWTBcTTMTMw\n"
            + "nsFCCFZsnSlCFBFflfflsztRPCqvvHPttRbHbhvPrrRr\n"
            + "SGNRLzpNpgNSNNlWFNwzqJfHfJHBtBdJhBJrHd\n"
            + "bQnjPTnjVdZtPPrfLP\n"
            + "TTnTccLnjGFcDNggFl\n"
            + "lBJmNzJlzmmQBlzgVVjLWRDfLjRsRLWWRS\n"
            + "vTMvTvtrfdhrrrPTdZwTTwtDqSSnWFWDFMMsRssjjsRqWD\n"
            + "ZpbvHbZddtbrdrdhcBmmpGQfBQgJNcmz\n"
            + "qsmhTmTVcDdcffhPhPvvzFhF\n"
            + "BNNlJbjWBWjtRtNljbmBBCpFzPlFPgpPfwFnlffnlPgg\n"
            + "JtBmmrrrRbDSrVqDqVSD\n"
            + "VmSgpSLgJjVDMrFrmMlfFmsG\n"
            + "bZWhZbzWcCwTWPRCwwwSPQzwMHnflHnGsMGnTrsflGMnlfTF\n"
            + "CqWhWqWCCWRRZQcLqDLpVDDLNStpgD\n"
            + "JwzTVzzcLzVJVVlJpVTwzGcrWhFjqsBjCjQFjWcCCjCjBF\n"
            + "MDSNQMtbSSnSbgbRDvnRNgvhmrqrjBCBtmCrCCWFqthhWm\n"
            + "bgMfNSSNZTwZQddGJZ\n"
            + "jjPgbFjjStjjPcSbrbtpvNrGnGDvBnMGvNDNGG\n"
            + "LwdZwsTdWTTmwDNCNppGBsnpBR\n"
            + "mWmHwZWhTTJWHBdQQWBjcFczSgjlSftjbtQPzg\n"
            + "fCBlrffzlCzcmfLDlfgRRnHScsHvRSQHMQvs\n"
            + "LthpZqtpVThZhGJtqTFvHsVnvsvMsggjHQjgQH\n"
            + "ZWFWGTLTWBNCWfDfmD\n"
            + "BpFqJrpcZZBDhDsNqMHhRG\n"
            + "zwlzPdmzPLhwvhMgsHnN\n"
            + "mPlWjlQfQjjllWtjQCWzCrBFJFTBcSNcJbbZfcZJSb\n"
            + "FpzNFTThBDChnnzNBCBNDzWGndgWqbJWVGqmPbJqQgQm\n"
            + "HQRctcvwgddVcJGd\n"
            + "LwRMZLjQfSRjFNzFSrhNsThS\n"
            + "WgRWVLWhFqgqgcgWHqLRWHVRbbbNwBmtBcNcwdwwBNwBzwBN\n"
            + "pSfssjDSrSvJpNJCztbJBtMNbt\n"
            + "TzsvGGnjGPsPjSTpDrPfPDSHhWqLgZZVHVhZZZZVQQFLnZ\n"
            + "sHjtPjQTtDbsfrrqWR\n"
            + "ZmccchvlvSvvZNMVNhvBLWRJJblWJWJlJfwHbwlL\n"
            + "hMMBzSMppVSzSNNmNgHjPgGPFTCpTTgTgG\n"
            + "rPQpCPPCQQZdcFhcZgzVJgwt\n"
            + "vDBSHmvHSSMlDWWmljnHBvFwzzcrwhVSJwVFtzcJJghw\n"
            + "bmmrsrsbsvNdCTdbPTdb\n"
            + "NgzBnsBNnfjgNvvfvWbtShSSFSMLJMFjjbPh\n"
            + "CCcRHdlQrQPLTJPLGP\n"
            + "HrDlRcqcDJCCDJHlcplrDJDfgfzBWWNZfvsnNqWwngZWwW\n"
            + "TggFVbjVTVzRwFFjjqBBqpzNztqcQqNNqN\n"
            + "SnZPrWndmShSZSPsnSLsJhpMQpcJtNqBClltqctC\n"
            + "mfWsGdnZZWmZmrLSfsrnmPggwtggRgGTVHvRwgFDjTGT\n"
            + "wQMZFQwppbPHPbLQJsgQNJJmBnds\n"
            + "qrSGvRRCvTzTDNnhNgmCgdBm\n"
            + "qzRrcRlGjvvzlzrvjcGqSSzMHWwVdPMWFpFMHMHWlPWMVV\n"
            + "BccsFzrBcsfpccccgFmQqlGNqCTLTlQnqgLlRG\n"
            + "MZbVSMddddSPPtdHPVJPJdTllqLNLGGTNCCRhTnHTQHh\n"
            + "DMwtbVZDZbSbpprcpccppwrq\n"
            + "bSZTdNqFjjzjqQMQ\n"
            + "WtRztLsWJpPLzrsMDlDQjMhVMC\n"
            + "pcgHRpHmWPJgLRzBJHBPPRBfvvfGNGvvFwfvSvfTmNNZfN\n"
            + "RjvBljWTTWTlqmBvHjGptRgccZcbPtcttbpzbn\n"
            + "VhDSDdJLJpSNNVVznPzzzSzcZFngZt\n"
            + "LsMdQNVMHsBHjqps\n"
            + "rSPSLTnSCClfSFCR\n"
            + "MwtZgwNBzzTjzZMbbmjNtwmBcRvFqQllqtQRlFRVqRqVVcvq\n"
            + "TsMhZsjNjBbTbBbwZLpDnHdDGdHWnpGHnh\n"
            + "LfdssTFBjFHSwlhzCcZZgMMfMhZZ\n"
            + "DmtDvrpmNStVvqpPczrZMMhZhhChCC\n"
            + "vJtJpQWvNVDtJFbHlJSlBbSF\n"
            + "PgvHLbcgRcGGHzRvgGgchBzsCZnmNZmZddrCrvdddZCZrF\n"
            + "JQBMjlStJrQsZFrNCZ\n"
            + "JSJTlqMtjptlplSSqJVDBqphwhhwHRPRggGbGzHbgzVRPH\n"
            + "pBsztsZdBsnWhntVnhtVTqTWNQlGGTGGFFlQFlTl\n"
            + "fDvLSMcbDbfMrGqFqSGwSQPzqz\n"
            + "zjcvLMMvffLjgggzfjjJCCLcdBtRphddBmmZBpCZZpZpmmhs\n"
            + "gmmSDplcPHDfHDlbVNrtCtCCNqHvTn\n"
            + "QGwJjzdPMzJhFLwnbvMqrTVCCMnvMv\n"
            + "LQQZdGjGdJhFBFQGjLGBJzzsBSWcPflllcfmDmfBsmBWPs\n"
            + "sMppbLDRMQbrTDTJjwcqnfnjwwnw\n"
            + "CgmFgSPHPzHgdmJWZZFzCzZZcVnGGnttWtVVVnccfjVqwVff\n"
            + "PhCChPSNgPgPJhPHhFZgsDNRspsvMNQLRvNDvpbD\n"
            + "pHnVnlRGVpfgpfgCpCTz\n"
            + "LCNQPqZCqNSSZCStzPgTmztwPfzwzT\n"
            + "dbSqhjhqQhNLQLFjLjGvFcRnCcsvRVvvsFnG\n"
            + "QTdnDTDQbCnMdbqdwSmJBljFJZhttJZMSh\n"
            + "HfNfLNzGLsgWBpGJthlZFBSB\n"
            + "ssRPHPfNsWHzZZvrvHfgLzNwnbbVVRwwRbVVcqDTddCVdD\n"
            + "ZhZBrJssjrNsbRtWpjwjlmlm\n"
            + "qTfHzGTfTGqqLGMdCCRcmmRRZcbPMccWmcRw\n"
            + "dVCZdDHdGHQhBVNJSsBhBF\n"
            + "NsplbGDbblHcbCpDlDGDPlPpJjdrVjgrvHnghvVdJrJdvvdn\n"
            + "tQFMZNWSmWFQRzQSwtzFmwFFJdVBghVrnBjVjBgrvVjMvrhJ\n"
            + "FFRmFZZRzQRmFLQSZZWQWFCPCNGcTCpGpfGfLTpblpff\n"
            + "dnhQHqQCnqWwNQCwCRRdJjjJVVPmVVJsJP\n"
            + "LccFRDgfMgLFBJVlmVVmgjrPzZ\n"
            + "pvfGpRpSpTnTQbvbTv\n"
            + "nwNlWwhWwNmJvQQdzdzZGMqDzn\n"
            + "rcVscPfrLcfvjTFcQDqGdZqMzMSHZHjS\n"
            + "LsfbbFcvVgRRblJRNR\n"
            + "Rmrrlmltcffhllfl\n"
            + "DDZMMMFZVsFsWZDSHhPPfgQbPPnQgcHctf\n"
            + "zGMGSBVDWCrvwjtBvm\n"
            + "DCZHwdDwNNGNZDZCjjtpTHLvtlgLbRLttlTL\n"
            + "BzPzBJffJJQgLlRgGztQ\n"
            + "PJffcJhJfNNSwFhGZC\n"
            + "blplfHbwZSfbcbwSbfVSHDHcNvdrvrWsCrvWVCRWnvNndtWW\n"
            + "hQzBTQLLMBWBsnsnNC\n"
            + "zMsgTjqTqPpZHbfp\n"
            + "ZLNNLtfZhRJQtpQhNRttZRqcGFcqGBzjrcqclGScFljjcj\n"
            + "VnvVVPMWHwgJCMvwdcGFdFrGcwzGBG\n"
            + "WHgPJJvWVTgnvgvTHmWCHmsNZRtNRDZpfZQffZZssR\n"
            + "rZgMFMVVjGbVSqZbhftLRDmCGRCNDCtm\n"
            + "cdddQzdWsWnQvzscnfRHmfnDNtLNChRmfH\n"
            + "zplDQdDzwszlDsWdPcldzMFFrFrBFgpqVBZgSgZFrF\n"
            + "gbzfbTvbJgbvzvTvJvJmzvjcBBQSfWDLCSBQQfLZWSCdBHHD\n"
            + "GhnMhsGrMNPPwnwsRPNsFCZDWHZdWBWHdrZLdCHBBC\n"
            + "PsnGsssGNsNRFsLGwMVNccJVmbjcjJblbzTVjlTz\n"
            + "RfBqNfVmPLTTTVRZMMBWjlMvBgbbMs\n"
            + "rHJzDwJdHzQgbMQlWMhd\n"
            + "HtJrpCcHflLPFfpq\n"
            + "SSGtmjQFStDbQbqGWJNnpZwgPsZjnJNNfZ\n"
            + "RdClRMhlldHdlvdThNgwfJNRspNwJpwZcN\n"
            + "CMBLgvvBLhrrBHTCVVLBQrWtbrDGmbtWGtzDQFGb\n"
            + "ZRRCqHpRdztLSqWz\n"
            + "hRsGjMVccGshPVDVcBmfgFFzggFgfBmWWtSd\n"
            + "PVjlGhcGJjGPsGMjjDVrMTpRnvRZlHnZNNQbHppTTC\n"
            + "QjbjWWlndRbwwwQWQdtpTVVZtzRPhHDzThhP\n"
            + "fFfLsvrLCrmvGlSfLSrlPHThDzTztHVtzDzGtTVh\n"
            + "fvrgsfccFLLLSvfMCCSWBjdMqdqNWBdBQNnWld\n"
            + "pjGPvvbllvqGvGjwMbpbRmgSmSwtRtShgSSWWQmW\n"
            + "DffTZLLzFFFTCRJMhWBzhmhgJt\n"
            + "CVVZLLTTsZTFCnMffMTFHffLVpGpNqGjNbNPljqVPcGNGlcv\n"
            + "rvJfztqQJqqrqHHwCzClTbBhDBBDrbSgphbVTrrV\n"
            + "FFGdNWFLGWMmLDbpRwVbgRBp\n"
            + "dmNGmZjMjQwtHCCw\n"
            + "MSGbqbqMbbGDhSSGDhLNBPNcrDPPfzfczPfrnv\n"
            + "rRwsrljslRgslwwgpssCjRtBNvnmPmBmccvmPnmzcP\n"
            + "CjVjsssJQpTCrCCgHJLMSZbhMhWGZhHG\n"
            + "JtBGBFGRVGVLLctRttthLFRBDQlDppljJwNQlpHHQqDHbHHN\n"
            + "szSZTrzdzTSMdzsmsqqQqwdbgDNqgQNjlN\n"
            + "SzmrlWPrlfPMsMZTPtCVCFRhhvhccLFPvL\n"
            + "chmbsMDMMcBnGbZBzZGL\n"
            + "JjjgJrJJggNgtrQSQBLjWBZlGnnB\n"
            + "rFNrFtFCRNVrrsHmMDcsLqMhMF\n"
            + "DLMwrBGgrBBDrcBcNBgWhpGhqVhhqSjqqqmjjp\n"
            + "JfJCZCdtlbZlHHbjWVpPmHWb\n"
            + "lTtZtnFQCztWFzJflZLcsrLFNDRNBcswcLMM\n"
            + "tsVttVCBsCcCqPqwvtqNPQjWDDWjzQQWnpJQSrWJJN\n"
            + "LMRdZvHGgMmZZGGLGLbhLhJpjWrSjndWJpSJrJppJnpj\n"
            + "RhRgLMlmgMGMFGLlTtcBvwcfFCtVvfFT\n"
            + "llBBmtncBglfqwsdwsjdbHwQHm\n"
            + "zGRhPJvFzhvFvMDGFvGPwSWWQpdpHSwSjWjHsWMw\n"
            + "JGFhDPrLTzhLhvFPzPjLjTzFlBqltnCqqBffcTgfnZfCfCnB\n"
            + "QWQGNHQBffCNDMPdRTDLPVMN\n"
            + "hrtlhtzZwJtwwgFgtlJthJJtZMqPVVpLmDVqRDmVPmMPVRTV\n"
            + "SJSSnJwJlsFFvcHSBbfLQHGL\n"
            + "zMNVzhNFsdNssmhlvtQvlttBlVGbTt\n"
            + "wHpFwjHjLFHlwtncTQlnwn\n"
            + "CCpjpqLCLqJggghqRmFsNRFmPszh\n"
            + "CTjmprmNcnmCNVQbstnstvbnQv\n"
            + "jqqdGhHgPRdfRRQvfLQffz\n"
            + "BGgqBhMdgqBHMDDqqMPwgdhSTJNjjmJWWCTCCmwTWZNpmZ\n"
            + "LqSDFFmdqDBDbbBHWl\n"
            + "dQcRpgwRQPngBWHbVWht\n"
            + "vdQMJQCQQvrJNqrTNsSZSmZT\n"
            + "cqrHcHHFNFPLLNPHLWnHHFHFjvlbZfWjSjBjZfSblhbBSbSf\n"
            + "VdVTGwTzTwTpMJslvjfsbbZSvnBClj\n"
            + "nJdGmmTpTTdmNQNNLPPmDFQL\n"
            + "VcjpTTtpcbThJBTTcjBvSPJzJlvPlwfJrgrgvw\n"
            + "dmshCNqnqdhmRsCsqCnrNgPPrPfzrNLfSwSgzl\n"
            + "ddQZdFnhsMttFTbDDD\n"
            + "hLThMTSdfMzzLzTLsFTbwtDvtsFTnttF\n"
            + "pZlNllPWrPCQPQlWNqjrqrjsnfDFbbtbstwswtvDnwtwjt\n"
            + "pCNNQBCClQrplrfHQpQdSRMSVRhJzRchRhGHSh\n"
            + "RZfVfRnTcPQWZcRVcRNSvljQsSSjNvvNqvss\n"
            + "pwbwgmqJhGlNvvzgMM\n"
            + "pthrhpmthmwhHHpLbbdrJmLWWRPTRZnCnPCPBnWTWTZq\n"
            + "nzsJJsMjGMMsQFbnNmLnmCfb\n"
            + "HlllPPTPlWTPDRRDRHcwwhrLLZfQmgmmQCFHvNZCgfggZQ\n"
            + "lPcNTwNWddGsMSttdjzj\n"
            + "bTbJZJDVFdqpBZTFTZJprdcsjjGszmjQszcjzDvsgccv\n"
            + "HHLnhMNCCPhfhCLMlPlnvgGfctscSvtSjGjztQtm\n"
            + "wWNQMPPMwlPHHPnnRLwWpJbrbbqbdppqJVJdZV\n"
            + "gpgpNnnrhwBVWFqgjqqF\n"
            + "ZCTsdRbCGZpZzCSGbWmtMBmWtqBBqdjjmq\n"
            + "LcsTSlplZrJNcQQPvH\n"
            + "DJDpMcqJDcDddNcJPGcJGFfnfZZmZZfRQZRNmVQVnBNn\n"
            + "WWThvSSHFshlSsHvgTHLlzBQfVWwmwnnfmRQWnQVRn\n"
            + "vljlgHjhstHbLhjLjrbPqMGJcJFJCMPrdF\n"
            + "pJlPMpMBrrMcnrBBMMrvdhdgFvmcFdWtmdtftg\n"
            + "bVVRmTRVTVVSVVVzZZqsggFHWTWtWffWFfWdtHdH\n"
            + "RjLQDSzmVsjRRZSZQrCMJDPwlnJJnGGrPB\n"
            + "GRgJtglPGlCrhQQrfW\n"
            + "vSjvZvZHNBjZSvwjvmvNDqhhFqhHrMhrHpfWqQfhpW\n"
            + "NBmwDSbZbvsNNBjmZfJzJgbVnGJbzVzPVRtL\n"
            + "QQZVQCdlVmdZnWmJBrLwSJRdggwdJr\n"
            + "DqHhPhcpvDqPFjhHjtFPssSJNfSBwBvffrgJwwJLBJbr\n"
            + "jpsHcptHsqtPttsjctpFhGlZwCMlWMmWGCWVQnTMVWmz\n"
            + "zzvnHjHWSfnvzpnfSRHdgrrsmWmhVrrwwbTrTmsrwm\n"
            + "NlLNGqqclqlZZCLCGGCPllJhhPJbrmpmrwVshFVsJbwr\n"
            + "DMLDNCZQCGLQGDtQpGtMjRdfdSRSSBtjtBjfjgjS\n"
            + "WBBJfjBQJjftGCbttVJptC\n"
            + "sdlmTHsqNsqpRtGcbWdbnR\n"
            + "svNMhmWHNmvmvHZWTvBQDgSSjDFPSBSFPP\n"
            + "mrlgqncgwHdqWWhRNtRttSvbRwwSvN\n"
            + "jZLCZVZzVcCTcpCDVSBBSbvvRFbfDBSDNS\n"
            + "VPJVpQjTZLjVLJJQGZTZGcQVghsGlmhshlqnghqrdrgldhlW\n"
            + "qwGDMqMFWbFbqbDwMgqgnjfnffffcTTjNnpTfBncZZ\n"
            + "lSdclSltlzPsJlhNNfTQPTmQhpPh\n"
            + "LtllsscLLLvvJlSzWGqwrDGqvbqMwMGb\n"
            + "bnfvnnQsVTdHQDmdNN\n"
            + "fwlttwrfSfLwdGZGmGND\n"
            + "qlPrjjplfSpjSltfttBBsvgzgbgnggBqWVvC\n"
            + "HHrBSmBqBHdHCFcQsc\n"
            + "WqtMDDnMMZhMhcsQVM\n"
            + "bqtbGDLLTTnRPwvGgBNmNrwvjm\n"
            + "RwWzWFwBcdSdMgJW\n"
            + "mrTjVQDQthQvjrvTmggFbbdgSJcJDFgSdg\n"
            + "phhFtvjNvFvTTvmTHZzlGlzZRZLBlzRp\n"
            + "cHlZmZmJSHZcTVGmvZVcGVHlNtbDNbtWFWdtlbCWbWtQDFdr\n"
            + "pwfwgRhngPjjtdWdNtFrdFwT\n"
            + "RTgMpfhBcMJGHqcz\n"
            + "dmCbpCLQVFmCRddCTFLCgZtWPNBhSNNwZWgWZvSwhN\n"
            + "rDzGDjJHhhwzThBS\n"
            + "rJrclsjjsJMJnJMLnbQQQFmRTqLVRT\n"
            + "TgFTGPtrWHzgCJDz\n"
            + "fQbfLwbbFbWjHJHWjd\n"
            + "LvQvwVfQvQhLLLLsmMBfLfBhqchtGFSNSFNqrSqPcqSGttSN\n"
            + "MsMmFgTVMMgMdFVMhdzWqCCBCWjWqBWqhzzL\n"
            + "nHfZDlbvcrDpcpcfDJbNJqGLbCjBmjLzJC\n"
            + "RnDZHwmmTwVMTsMS\n"
            + "NpdpdnjNCRjBnHRPpBDnhSdSwFFLFdScFFWcFWLd\n"
            + "stqMrMZtsQMJmMqvrtqMbstQVchPFWgFVVFVwfWJcSSWVSSV\n"
            + "MQrZzbvMrrrZZtZmstMtMsDRRjPHCGTjBnzpnDHTCGjG\n"
            + "ClGGvDMGMNhNSmFVPbpgFgmFgZPb\n"
            + "WhTTLWsBBWTcrPpggtQpsQFpVb\n"
            + "fBRTqWLjTrzDNhMvCSGDzl\n"
            + "jbzjttVzpbWzWVbTtzWzVwPbPPcwDDccccFNFLMFsm\n"
            + "rlghJZHmCHvHJvRLSNLhhhccNPwcMP\n"
            + "QffmBZRBGtVTBdTG\n"
            + "bDRqHwwRpNPnbppn\n"
            + "FqrlQSQJSVsQrSCmpdPNpcNCcP\n"
            + "jFZjrssjBhrZVhJLLGHfMHfwtqRjMqRTvD\n"
            + "SMMCTBzFfSRhTThCSMRSzzHnJgqGDHQgGVDnqrqnqqnqcQ\n"
            + "ljvjpWPbrWWtrbmDVDlmnDnqVmgJ\n"
            + "bNjsNPrNPtswfZzfTSTBwhSM\n"
            + "hNMNdssdMqdTQchqgNZzHtwmwGHHzmQZGHDH\n"
            + "JrbJvJrvLrPjrPCVCjRBLPbzfRFZmzwHgFHmGHmwFwzFZR\n"
            + "rpbrvVjPCBbCJrCSLSPsTlphNncMglcNTMWMql\n"
            + "fGWGHbrllCCWWllFNPQSZvdPSvdZTffZ\n"
            + "tqssVjJMJWzWVvSvWS\n"
            + "qtwMwDWjnRRwssWjngwjjnhhDcCLhhCFHlcmcbCHFmDC\n"
            + "rFTdFjdRDTTlDWCqvhwLhwZdLS\n"
            + "QzfJfnfsbsJHMnNmHhVpCZwSQSWqSqVQhS\n"
            + "nJnczsHzNMmBJnbnbNwnfzJfcDTltllRTgPlFlgPrTDjPRGl\n"
            + "ZLCGDvvJlvGChSPZWPSsZWdRRN\n"
            + "rQccBwcccnHmQggnVLPLWpgVWPpWzSRs\n"
            + "fmwTfTHnMBTfJDbfftJLvhlL";
}
