package day05;

import java.util.ArrayDeque;

public class Day05Task1 {
    public static void main(String[] args) {
        final int stackCount = 9;
        @SuppressWarnings("unchecked")
        ArrayDeque<Character>[] stacks = new ArrayDeque[stackCount];
        @SuppressWarnings("unchecked")
        ArrayDeque<Character>[] stacks2 = new ArrayDeque[stackCount];
        for (int i = 0; i < stackCount; i++) {
            stacks[i] = new ArrayDeque<>();
            stacks2[i] = new ArrayDeque<>();
        }
        String[] initialLines = initial.split("\n");
        for (int i = initialLines.length - 1; i >= 0; i--) {
            String line = initialLines[i];
            for (int j = 0; j < stackCount; j++) {
                char element = line.charAt(1 + j * 4);
                if (element != ' ') {
                    stacks[j].push(element);
                    stacks2[j].push(element);
                }
            }
        }
        ArrayDeque<Character> temp = new ArrayDeque<>();
        for (String line : input.split("\n")) {
            line = line.substring(5);
            String[] parts = line.split(" from ");
            String[] parts2 = parts[1].split(" to ");
            int amount = Integer.parseInt(parts[0]);
            int from = Integer.parseInt(parts2[0]) - 1;
            int to = Integer.parseInt(parts2[1]) - 1;
            for (int i = 0; i < amount; i++) {
                stacks[to].push(stacks[from].pop());
                temp.push(stacks2[from].pop());
            }
            while (!temp.isEmpty()) {
                stacks2[to].push(temp.pop());
            }
        }

        StringBuilder topmost = new StringBuilder();
        StringBuilder topmost2 = new StringBuilder();
        for (int j = 0; j < stackCount; j++) {
            topmost.append(stacks[j].peek().charValue());
            topmost2.append(stacks2[j].peek().charValue());
        }
        System.out.println(topmost);
        System.out.println(topmost2);
    }

    private static final String initial = ""
            + "        [H]     [W] [B]            \n"
            + "    [D] [B]     [L] [G] [N]        \n"
            + "[P] [J] [T]     [M] [R] [D]        \n"
            + "[V] [F] [V]     [F] [Z] [B]     [C]\n"
            + "[Z] [V] [S]     [G] [H] [C] [Q] [R]\n"
            + "[W] [W] [L] [J] [B] [V] [P] [B] [Z]\n"
            + "[D] [S] [M] [S] [Z] [W] [J] [T] [G]\n"
            + "[T] [L] [Z] [R] [C] [Q] [V] [P] [H]";

    private static final String input = "move 3 from 2 to 9\n"
            + "move 1 from 1 to 6\n"
            + "move 6 from 6 to 7\n"
            + "move 13 from 7 to 6\n"
            + "move 2 from 4 to 5\n"
            + "move 1 from 4 to 3\n"
            + "move 5 from 9 to 8\n"
            + "move 1 from 8 to 5\n"
            + "move 3 from 1 to 6\n"
            + "move 2 from 1 to 8\n"
            + "move 1 from 2 to 1\n"
            + "move 1 from 9 to 3\n"
            + "move 2 from 9 to 8\n"
            + "move 2 from 5 to 9\n"
            + "move 4 from 5 to 4\n"
            + "move 10 from 8 to 4\n"
            + "move 5 from 6 to 2\n"
            + "move 5 from 5 to 9\n"
            + "move 7 from 3 to 7\n"
            + "move 1 from 9 to 8\n"
            + "move 1 from 1 to 9\n"
            + "move 1 from 7 to 3\n"
            + "move 3 from 8 to 9\n"
            + "move 8 from 6 to 7\n"
            + "move 3 from 9 to 4\n"
            + "move 3 from 2 to 6\n"
            + "move 6 from 6 to 3\n"
            + "move 10 from 7 to 9\n"
            + "move 1 from 7 to 5\n"
            + "move 1 from 5 to 7\n"
            + "move 2 from 3 to 6\n"
            + "move 8 from 4 to 2\n"
            + "move 7 from 4 to 3\n"
            + "move 5 from 2 to 3\n"
            + "move 2 from 4 to 6\n"
            + "move 6 from 2 to 8\n"
            + "move 14 from 9 to 1\n"
            + "move 6 from 3 to 2\n"
            + "move 7 from 3 to 7\n"
            + "move 4 from 2 to 3\n"
            + "move 1 from 6 to 5\n"
            + "move 3 from 6 to 5\n"
            + "move 2 from 2 to 4\n"
            + "move 3 from 1 to 2\n"
            + "move 2 from 4 to 1\n"
            + "move 3 from 5 to 6\n"
            + "move 1 from 9 to 6\n"
            + "move 1 from 2 to 6\n"
            + "move 7 from 7 to 4\n"
            + "move 5 from 8 to 1\n"
            + "move 11 from 3 to 5\n"
            + "move 2 from 2 to 5\n"
            + "move 8 from 5 to 1\n"
            + "move 4 from 7 to 2\n"
            + "move 2 from 6 to 8\n"
            + "move 3 from 2 to 4\n"
            + "move 1 from 8 to 3\n"
            + "move 1 from 3 to 2\n"
            + "move 11 from 1 to 8\n"
            + "move 4 from 6 to 5\n"
            + "move 1 from 4 to 1\n"
            + "move 2 from 6 to 4\n"
            + "move 14 from 1 to 9\n"
            + "move 1 from 1 to 6\n"
            + "move 1 from 1 to 9\n"
            + "move 10 from 4 to 3\n"
            + "move 3 from 3 to 2\n"
            + "move 8 from 8 to 9\n"
            + "move 1 from 4 to 5\n"
            + "move 8 from 5 to 8\n"
            + "move 10 from 9 to 5\n"
            + "move 5 from 3 to 2\n"
            + "move 1 from 3 to 7\n"
            + "move 1 from 2 to 5\n"
            + "move 6 from 2 to 3\n"
            + "move 7 from 3 to 5\n"
            + "move 1 from 6 to 9\n"
            + "move 2 from 5 to 9\n"
            + "move 4 from 2 to 9\n"
            + "move 1 from 2 to 1\n"
            + "move 1 from 1 to 5\n"
            + "move 1 from 7 to 4\n"
            + "move 17 from 9 to 1\n"
            + "move 4 from 1 to 5\n"
            + "move 9 from 5 to 8\n"
            + "move 21 from 8 to 6\n"
            + "move 1 from 4 to 6\n"
            + "move 3 from 5 to 1\n"
            + "move 10 from 1 to 5\n"
            + "move 12 from 5 to 3\n"
            + "move 3 from 3 to 6\n"
            + "move 5 from 5 to 7\n"
            + "move 5 from 5 to 9\n"
            + "move 5 from 7 to 5\n"
            + "move 2 from 5 to 7\n"
            + "move 1 from 8 to 5\n"
            + "move 1 from 7 to 3\n"
            + "move 3 from 1 to 7\n"
            + "move 11 from 6 to 5\n"
            + "move 1 from 7 to 3\n"
            + "move 5 from 9 to 7\n"
            + "move 8 from 3 to 6\n"
            + "move 4 from 9 to 6\n"
            + "move 3 from 1 to 6\n"
            + "move 1 from 9 to 5\n"
            + "move 6 from 5 to 1\n"
            + "move 1 from 1 to 6\n"
            + "move 3 from 1 to 3\n"
            + "move 2 from 1 to 2\n"
            + "move 19 from 6 to 1\n"
            + "move 2 from 5 to 9\n"
            + "move 5 from 3 to 1\n"
            + "move 1 from 5 to 6\n"
            + "move 5 from 6 to 7\n"
            + "move 3 from 7 to 9\n"
            + "move 6 from 5 to 9\n"
            + "move 1 from 5 to 6\n"
            + "move 4 from 6 to 9\n"
            + "move 2 from 2 to 1\n"
            + "move 1 from 3 to 2\n"
            + "move 1 from 2 to 7\n"
            + "move 7 from 7 to 6\n"
            + "move 21 from 1 to 3\n"
            + "move 2 from 7 to 8\n"
            + "move 7 from 3 to 2\n"
            + "move 2 from 7 to 9\n"
            + "move 8 from 3 to 8\n"
            + "move 4 from 3 to 1\n"
            + "move 6 from 1 to 9\n"
            + "move 7 from 2 to 9\n"
            + "move 1 from 3 to 6\n"
            + "move 1 from 8 to 7\n"
            + "move 1 from 1 to 6\n"
            + "move 12 from 6 to 9\n"
            + "move 1 from 3 to 6\n"
            + "move 1 from 7 to 5\n"
            + "move 1 from 1 to 9\n"
            + "move 1 from 5 to 9\n"
            + "move 39 from 9 to 4\n"
            + "move 3 from 9 to 6\n"
            + "move 1 from 9 to 6\n"
            + "move 7 from 8 to 4\n"
            + "move 1 from 9 to 8\n"
            + "move 44 from 4 to 1\n"
            + "move 1 from 6 to 3\n"
            + "move 28 from 1 to 8\n"
            + "move 15 from 8 to 1\n"
            + "move 1 from 3 to 2\n"
            + "move 11 from 1 to 5\n"
            + "move 1 from 4 to 7\n"
            + "move 1 from 4 to 5\n"
            + "move 16 from 1 to 6\n"
            + "move 1 from 2 to 6\n"
            + "move 12 from 8 to 2\n"
            + "move 1 from 7 to 4\n"
            + "move 3 from 2 to 4\n"
            + "move 7 from 2 to 4\n"
            + "move 4 from 1 to 6\n"
            + "move 10 from 5 to 6\n"
            + "move 1 from 1 to 5\n"
            + "move 3 from 5 to 9\n"
            + "move 3 from 8 to 7\n"
            + "move 1 from 2 to 3\n"
            + "move 1 from 2 to 4\n"
            + "move 3 from 7 to 4\n"
            + "move 30 from 6 to 8\n"
            + "move 1 from 3 to 7\n"
            + "move 20 from 8 to 4\n"
            + "move 1 from 7 to 3\n"
            + "move 1 from 9 to 8\n"
            + "move 25 from 4 to 6\n"
            + "move 1 from 3 to 5\n"
            + "move 8 from 8 to 5\n"
            + "move 3 from 8 to 4\n"
            + "move 2 from 9 to 5\n"
            + "move 2 from 5 to 2\n"
            + "move 21 from 6 to 4\n"
            + "move 2 from 2 to 6\n"
            + "move 28 from 4 to 5\n"
            + "move 1 from 8 to 6\n"
            + "move 5 from 4 to 8\n"
            + "move 3 from 6 to 7\n"
            + "move 15 from 5 to 2\n"
            + "move 3 from 7 to 6\n"
            + "move 1 from 4 to 3\n"
            + "move 17 from 5 to 1\n"
            + "move 1 from 3 to 4\n"
            + "move 1 from 4 to 8\n"
            + "move 4 from 2 to 4\n"
            + "move 4 from 4 to 1\n"
            + "move 5 from 6 to 8\n"
            + "move 11 from 8 to 3\n"
            + "move 4 from 6 to 7\n"
            + "move 5 from 3 to 2\n"
            + "move 4 from 3 to 1\n"
            + "move 25 from 1 to 7\n"
            + "move 3 from 6 to 7\n"
            + "move 8 from 2 to 3\n"
            + "move 11 from 7 to 2\n"
            + "move 2 from 2 to 7\n"
            + "move 16 from 2 to 6\n"
            + "move 1 from 2 to 8\n"
            + "move 1 from 7 to 6\n"
            + "move 1 from 5 to 2\n"
            + "move 16 from 6 to 2\n"
            + "move 3 from 5 to 7\n"
            + "move 6 from 2 to 8\n"
            + "move 1 from 5 to 4\n"
            + "move 1 from 4 to 3\n"
            + "move 4 from 8 to 9\n"
            + "move 4 from 3 to 9\n"
            + "move 2 from 6 to 2\n"
            + "move 6 from 2 to 4\n"
            + "move 1 from 9 to 7\n"
            + "move 1 from 2 to 8\n"
            + "move 7 from 3 to 6\n"
            + "move 4 from 2 to 6\n"
            + "move 2 from 9 to 5\n"
            + "move 1 from 2 to 4\n"
            + "move 6 from 6 to 9\n"
            + "move 2 from 5 to 1\n"
            + "move 1 from 1 to 4\n"
            + "move 1 from 9 to 4\n"
            + "move 2 from 7 to 6\n"
            + "move 1 from 2 to 5\n"
            + "move 1 from 5 to 9\n"
            + "move 4 from 8 to 1\n"
            + "move 7 from 9 to 8\n"
            + "move 3 from 1 to 7\n"
            + "move 1 from 8 to 3\n"
            + "move 4 from 9 to 6\n"
            + "move 6 from 8 to 1\n"
            + "move 6 from 1 to 2\n"
            + "move 1 from 1 to 9\n"
            + "move 1 from 1 to 7\n"
            + "move 21 from 7 to 5\n"
            + "move 11 from 5 to 3\n"
            + "move 1 from 9 to 5\n"
            + "move 1 from 2 to 8\n"
            + "move 5 from 7 to 5\n"
            + "move 10 from 3 to 9\n"
            + "move 1 from 8 to 5\n"
            + "move 8 from 4 to 2\n"
            + "move 1 from 3 to 4\n"
            + "move 2 from 7 to 3\n"
            + "move 5 from 5 to 3\n"
            + "move 5 from 9 to 8\n"
            + "move 10 from 6 to 2\n"
            + "move 1 from 6 to 4\n"
            + "move 1 from 9 to 4\n"
            + "move 4 from 9 to 3\n"
            + "move 19 from 2 to 5\n"
            + "move 2 from 4 to 5\n"
            + "move 11 from 5 to 1\n"
            + "move 15 from 5 to 2\n"
            + "move 4 from 8 to 1\n"
            + "move 12 from 1 to 5\n"
            + "move 1 from 8 to 1\n"
            + "move 1 from 4 to 8\n"
            + "move 3 from 1 to 3\n"
            + "move 8 from 5 to 4\n"
            + "move 7 from 3 to 9\n"
            + "move 4 from 3 to 5\n"
            + "move 4 from 4 to 1\n"
            + "move 3 from 9 to 3\n"
            + "move 2 from 4 to 1\n"
            + "move 4 from 3 to 8\n"
            + "move 4 from 2 to 3\n"
            + "move 1 from 9 to 5\n"
            + "move 4 from 8 to 6\n"
            + "move 2 from 4 to 3\n"
            + "move 1 from 4 to 5\n"
            + "move 5 from 3 to 4\n"
            + "move 3 from 3 to 6\n"
            + "move 5 from 1 to 6\n"
            + "move 2 from 4 to 6\n"
            + "move 1 from 9 to 2\n"
            + "move 7 from 6 to 3\n"
            + "move 1 from 8 to 9\n"
            + "move 2 from 1 to 4\n"
            + "move 2 from 4 to 7\n"
            + "move 4 from 6 to 4\n"
            + "move 5 from 3 to 7\n"
            + "move 1 from 7 to 2\n"
            + "move 3 from 6 to 7\n"
            + "move 1 from 4 to 5\n"
            + "move 4 from 2 to 6\n"
            + "move 3 from 6 to 9\n"
            + "move 1 from 6 to 5\n"
            + "move 1 from 9 to 2\n"
            + "move 5 from 9 to 3\n"
            + "move 11 from 5 to 1\n"
            + "move 3 from 7 to 8\n"
            + "move 2 from 8 to 9\n"
            + "move 4 from 5 to 1\n"
            + "move 10 from 2 to 7\n"
            + "move 5 from 3 to 7\n"
            + "move 1 from 9 to 3\n"
            + "move 6 from 1 to 7\n"
            + "move 22 from 7 to 9\n"
            + "move 3 from 2 to 4\n"
            + "move 4 from 5 to 3\n"
            + "move 1 from 8 to 4\n"
            + "move 5 from 4 to 7\n"
            + "move 19 from 9 to 8\n"
            + "move 2 from 1 to 5\n"
            + "move 2 from 4 to 5\n"
            + "move 2 from 4 to 9\n"
            + "move 4 from 9 to 2\n"
            + "move 4 from 7 to 3\n"
            + "move 5 from 7 to 5\n"
            + "move 7 from 3 to 7\n"
            + "move 2 from 8 to 4\n"
            + "move 3 from 4 to 7\n"
            + "move 12 from 8 to 1\n"
            + "move 4 from 3 to 7\n"
            + "move 1 from 3 to 6\n"
            + "move 1 from 6 to 1\n"
            + "move 1 from 5 to 9\n"
            + "move 3 from 9 to 3\n"
            + "move 2 from 2 to 4\n"
            + "move 3 from 8 to 3\n"
            + "move 2 from 4 to 7\n"
            + "move 7 from 5 to 1\n"
            + "move 2 from 8 to 3\n"
            + "move 8 from 7 to 9\n"
            + "move 2 from 9 to 7\n"
            + "move 3 from 9 to 5\n"
            + "move 11 from 1 to 2\n"
            + "move 5 from 3 to 8\n"
            + "move 16 from 1 to 5\n"
            + "move 1 from 9 to 8\n"
            + "move 3 from 3 to 2\n"
            + "move 6 from 2 to 6\n"
            + "move 6 from 7 to 4\n"
            + "move 2 from 5 to 2\n"
            + "move 6 from 4 to 9\n"
            + "move 11 from 5 to 7\n"
            + "move 2 from 6 to 5\n"
            + "move 9 from 5 to 1\n"
            + "move 2 from 8 to 5\n"
            + "move 13 from 7 to 4\n"
            + "move 6 from 1 to 5\n"
            + "move 10 from 2 to 9\n"
            + "move 1 from 4 to 5\n"
            + "move 4 from 6 to 9\n"
            + "move 3 from 2 to 4\n"
            + "move 2 from 8 to 2\n"
            + "move 15 from 4 to 5\n"
            + "move 1 from 2 to 8\n"
            + "move 1 from 2 to 3\n"
            + "move 2 from 8 to 7\n"
            + "move 3 from 7 to 1\n"
            + "move 1 from 7 to 8\n"
            + "move 3 from 5 to 9\n"
            + "move 1 from 7 to 1\n"
            + "move 21 from 5 to 2\n"
            + "move 3 from 9 to 1\n"
            + "move 5 from 1 to 4\n"
            + "move 1 from 3 to 4\n"
            + "move 1 from 8 to 5\n"
            + "move 1 from 8 to 9\n"
            + "move 1 from 5 to 3\n"
            + "move 5 from 2 to 5\n"
            + "move 5 from 5 to 3\n"
            + "move 7 from 9 to 2\n"
            + "move 3 from 3 to 6\n"
            + "move 2 from 1 to 4\n"
            + "move 1 from 3 to 4\n"
            + "move 2 from 3 to 2\n"
            + "move 25 from 2 to 1\n"
            + "move 11 from 9 to 2\n"
            + "move 9 from 2 to 8\n"
            + "move 4 from 9 to 5\n"
            + "move 6 from 4 to 3\n"
            + "move 3 from 3 to 5\n"
            + "move 9 from 8 to 2\n"
            + "move 3 from 4 to 3\n"
            + "move 1 from 9 to 4\n"
            + "move 4 from 3 to 8\n"
            + "move 2 from 8 to 1\n"
            + "move 3 from 5 to 9\n"
            + "move 2 from 8 to 1\n"
            + "move 4 from 2 to 9\n"
            + "move 6 from 9 to 4\n"
            + "move 1 from 9 to 2\n"
            + "move 1 from 6 to 4\n"
            + "move 3 from 4 to 3\n"
            + "move 2 from 3 to 9\n"
            + "move 3 from 1 to 9\n"
            + "move 2 from 2 to 7\n"
            + "move 2 from 7 to 2\n"
            + "move 2 from 3 to 2\n"
            + "move 5 from 9 to 7\n"
            + "move 2 from 7 to 2\n"
            + "move 28 from 1 to 7\n"
            + "move 1 from 1 to 9\n"
            + "move 10 from 2 to 5\n"
            + "move 1 from 9 to 5\n"
            + "move 14 from 7 to 1\n"
            + "move 6 from 1 to 6\n"
            + "move 12 from 7 to 9\n"
            + "move 6 from 1 to 5\n"
            + "move 1 from 3 to 8\n"
            + "move 4 from 7 to 1\n"
            + "move 4 from 4 to 8\n"
            + "move 4 from 6 to 1\n"
            + "move 1 from 2 to 8\n"
            + "move 1 from 2 to 1\n"
            + "move 1 from 6 to 1\n"
            + "move 5 from 9 to 8\n"
            + "move 16 from 5 to 7\n"
            + "move 2 from 7 to 1\n"
            + "move 6 from 8 to 1\n"
            + "move 2 from 9 to 4\n"
            + "move 2 from 1 to 3\n"
            + "move 1 from 6 to 8\n"
            + "move 2 from 5 to 3\n"
            + "move 3 from 5 to 7\n"
            + "move 4 from 8 to 7\n"
            + "move 4 from 9 to 8\n"
            + "move 6 from 8 to 6\n"
            + "move 10 from 7 to 8\n"
            + "move 1 from 9 to 1\n"
            + "move 11 from 7 to 6\n"
            + "move 2 from 3 to 9\n"
            + "move 1 from 3 to 4\n"
            + "move 4 from 1 to 2\n"
            + "move 3 from 2 to 3\n"
            + "move 1 from 9 to 1\n"
            + "move 3 from 4 to 2\n"
            + "move 9 from 6 to 4\n"
            + "move 2 from 3 to 5\n"
            + "move 8 from 4 to 9\n"
            + "move 4 from 1 to 8\n"
            + "move 3 from 8 to 2\n"
            + "move 2 from 2 to 6\n"
            + "move 1 from 7 to 2\n"
            + "move 11 from 6 to 5\n"
            + "move 7 from 8 to 6\n"
            + "move 7 from 5 to 8\n"
            + "move 5 from 8 to 5\n"
            + "move 1 from 2 to 5\n"
            + "move 3 from 5 to 7\n"
            + "move 8 from 5 to 6\n"
            + "move 2 from 4 to 5\n"
            + "move 1 from 7 to 9\n"
            + "move 2 from 3 to 8\n"
            + "move 3 from 8 to 5\n"
            + "move 13 from 6 to 2\n"
            + "move 2 from 8 to 5\n"
            + "move 5 from 1 to 9\n"
            + "move 3 from 6 to 4\n"
            + "move 5 from 5 to 8\n"
            + "move 1 from 5 to 4\n"
            + "move 4 from 1 to 4\n"
            + "move 1 from 7 to 2\n"
            + "move 12 from 9 to 7\n"
            + "move 2 from 9 to 1\n"
            + "move 3 from 8 to 3\n"
            + "move 1 from 5 to 4\n"
            + "move 3 from 8 to 9\n"
            + "move 2 from 4 to 7\n"
            + "move 4 from 9 to 5\n"
            + "move 5 from 4 to 9\n"
            + "move 3 from 9 to 2\n"
            + "move 1 from 9 to 4\n"
            + "move 1 from 9 to 3\n"
            + "move 12 from 7 to 4\n"
            + "move 1 from 4 to 8\n"
            + "move 1 from 8 to 1\n"
            + "move 1 from 5 to 4\n"
            + "move 2 from 3 to 5\n"
            + "move 11 from 2 to 3\n"
            + "move 4 from 5 to 7\n"
            + "move 7 from 7 to 2\n"
            + "move 1 from 1 to 9\n"
            + "move 1 from 8 to 3\n"
            + "move 1 from 9 to 1\n"
            + "move 2 from 1 to 5\n"
            + "move 2 from 5 to 4\n"
            + "move 1 from 8 to 1\n"
            + "move 2 from 5 to 8\n"
            + "move 5 from 1 to 9\n"
            + "move 11 from 3 to 9\n"
            + "move 1 from 3 to 6\n"
            + "move 1 from 6 to 3\n"
            + "move 3 from 3 to 6\n"
            + "move 3 from 2 to 6\n"
            + "move 13 from 9 to 7\n"
            + "move 2 from 6 to 1\n"
            + "move 8 from 4 to 9\n"
            + "move 7 from 4 to 2\n"
            + "move 2 from 8 to 6\n"
            + "move 1 from 1 to 9\n"
            + "move 5 from 2 to 1\n"
            + "move 2 from 1 to 3\n"
            + "move 10 from 2 to 8\n"
            + "move 3 from 9 to 3\n"
            + "move 1 from 7 to 4\n"
            + "move 6 from 7 to 5";
}
