package day10;

public class Day10Task1 {
    static int registerX = 1;
    static int tick = 0;
    static int signalStrength = 0;

    public static void main(String[] args) {
        for (String line : INPUT.split("\n")) {
            if (line.equals("noop")) {
                tick();
            } else if (line.startsWith("addx ")) {
                int delta = Integer.parseInt(line.substring(5));
                tick();
                tick();
                registerX += delta;
            } else {
                throw new IllegalArgumentException(line);
            }
        }
        System.out.println(signalStrength);
    }

    private static void tick() {
        tick++;
        if ((tick + 20) % 40 == 0) {
            signalStrength += registerX * tick;
        }
        int d = ((tick - 1) % 40) - registerX;
        System.out.print(Math.abs(d) <= 1 ? "#" : " ");
        if (tick % 40 == 0) {
            System.out.println();
        }
    }

    public static final String INPUT2 = "addx 15\n"
            + "addx -11\n"
            + "addx 6\n"
            + "addx -3\n"
            + "addx 5\n"
            + "addx -1\n"
            + "addx -8\n"
            + "addx 13\n"
            + "addx 4\n"
            + "noop\n"
            + "addx -1\n"
            + "addx 5\n"
            + "addx -1\n"
            + "addx 5\n"
            + "addx -1\n"
            + "addx 5\n"
            + "addx -1\n"
            + "addx 5\n"
            + "addx -1\n"
            + "addx -35\n"
            + "addx 1\n"
            + "addx 24\n"
            + "addx -19\n"
            + "addx 1\n"
            + "addx 16\n"
            + "addx -11\n"
            + "noop\n"
            + "noop\n"
            + "addx 21\n"
            + "addx -15\n"
            + "noop\n"
            + "noop\n"
            + "addx -3\n"
            + "addx 9\n"
            + "addx 1\n"
            + "addx -3\n"
            + "addx 8\n"
            + "addx 1\n"
            + "addx 5\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "addx -36\n"
            + "noop\n"
            + "addx 1\n"
            + "addx 7\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "addx 2\n"
            + "addx 6\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "addx 1\n"
            + "noop\n"
            + "noop\n"
            + "addx 7\n"
            + "addx 1\n"
            + "noop\n"
            + "addx -13\n"
            + "addx 13\n"
            + "addx 7\n"
            + "noop\n"
            + "addx 1\n"
            + "addx -33\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "addx 2\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "addx 8\n"
            + "noop\n"
            + "addx -1\n"
            + "addx 2\n"
            + "addx 1\n"
            + "noop\n"
            + "addx 17\n"
            + "addx -9\n"
            + "addx 1\n"
            + "addx 1\n"
            + "addx -3\n"
            + "addx 11\n"
            + "noop\n"
            + "noop\n"
            + "addx 1\n"
            + "noop\n"
            + "addx 1\n"
            + "noop\n"
            + "noop\n"
            + "addx -13\n"
            + "addx -19\n"
            + "addx 1\n"
            + "addx 3\n"
            + "addx 26\n"
            + "addx -30\n"
            + "addx 12\n"
            + "addx -1\n"
            + "addx 3\n"
            + "addx 1\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "addx -9\n"
            + "addx 18\n"
            + "addx 1\n"
            + "addx 2\n"
            + "noop\n"
            + "noop\n"
            + "addx 9\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "addx -1\n"
            + "addx 2\n"
            + "addx -37\n"
            + "addx 1\n"
            + "addx 3\n"
            + "noop\n"
            + "addx 15\n"
            + "addx -21\n"
            + "addx 22\n"
            + "addx -6\n"
            + "addx 1\n"
            + "noop\n"
            + "addx 2\n"
            + "addx 1\n"
            + "noop\n"
            + "addx -10\n"
            + "noop\n"
            + "noop\n"
            + "addx 20\n"
            + "addx 1\n"
            + "addx 2\n"
            + "addx 2\n"
            + "addx -6\n"
            + "addx -11\n"
            + "noop\n"
            + "noop\n"
            + "noop";

    public static final String INPUT = "noop\n"
            + "noop\n"
            + "addx 5\n"
            + "addx 21\n"
            + "addx -16\n"
            + "noop\n"
            + "addx 1\n"
            + "noop\n"
            + "noop\n"
            + "addx 4\n"
            + "addx 1\n"
            + "addx 4\n"
            + "addx 1\n"
            + "noop\n"
            + "addx 4\n"
            + "addx -9\n"
            + "noop\n"
            + "addx 19\n"
            + "addx -5\n"
            + "noop\n"
            + "noop\n"
            + "addx 5\n"
            + "addx 1\n"
            + "addx -38\n"
            + "addx 5\n"
            + "addx -2\n"
            + "addx 2\n"
            + "noop\n"
            + "noop\n"
            + "addx 7\n"
            + "addx 9\n"
            + "addx 20\n"
            + "addx -3\n"
            + "addx -18\n"
            + "addx 2\n"
            + "addx 5\n"
            + "noop\n"
            + "noop\n"
            + "addx -2\n"
            + "noop\n"
            + "noop\n"
            + "addx 7\n"
            + "addx 3\n"
            + "addx -2\n"
            + "addx 2\n"
            + "addx -28\n"
            + "addx -7\n"
            + "addx 5\n"
            + "noop\n"
            + "addx 2\n"
            + "addx 32\n"
            + "addx -27\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "addx 7\n"
            + "noop\n"
            + "addx 22\n"
            + "addx -19\n"
            + "noop\n"
            + "addx 5\n"
            + "noop\n"
            + "addx -7\n"
            + "addx 17\n"
            + "addx -7\n"
            + "noop\n"
            + "addx -20\n"
            + "addx 27\n"
            + "noop\n"
            + "addx -16\n"
            + "addx -20\n"
            + "addx 1\n"
            + "noop\n"
            + "addx 3\n"
            + "addx 15\n"
            + "addx -8\n"
            + "addx -2\n"
            + "addx -6\n"
            + "addx 14\n"
            + "addx 4\n"
            + "noop\n"
            + "noop\n"
            + "addx -17\n"
            + "addx 22\n"
            + "noop\n"
            + "addx 5\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "addx 2\n"
            + "noop\n"
            + "addx 3\n"
            + "addx -32\n"
            + "addx -5\n"
            + "noop\n"
            + "addx 4\n"
            + "addx 3\n"
            + "addx -2\n"
            + "addx 34\n"
            + "addx -27\n"
            + "addx 5\n"
            + "addx 16\n"
            + "addx -18\n"
            + "addx 7\n"
            + "noop\n"
            + "addx -2\n"
            + "addx -1\n"
            + "addx 8\n"
            + "addx 14\n"
            + "addx -9\n"
            + "noop\n"
            + "addx -15\n"
            + "addx 16\n"
            + "addx 2\n"
            + "addx -35\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "addx 3\n"
            + "addx 4\n"
            + "noop\n"
            + "addx 1\n"
            + "addx 4\n"
            + "addx 1\n"
            + "noop\n"
            + "addx 4\n"
            + "addx 2\n"
            + "addx 3\n"
            + "addx -5\n"
            + "addx 19\n"
            + "addx -9\n"
            + "addx 2\n"
            + "addx 4\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "noop\n"
            + "addx 3\n"
            + "addx 2\n"
            + "noop\n"
            + "noop\n"
            + "noop";
}
